//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/File.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/File.fbs
//! file ident: //File.fbs
//! typename    org.apache.arrow.flatbuf.Block
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Block = @import("Block.fb.zig").Block;
                const BlockT = @import("Block.fb.zig").BlockT;
            };
        };
    };
};

/// Describes where an IPC message is written in a file container.
///
/// `offset` points to the start of the encapsulated message in the file.
/// `metaDataLength` is the number of metadata bytes for that message
/// (including the encapsulated message prefix).
/// `bodyLength` is the body byte length from the Message metadata.
pub const BlockT = struct {
    offset: i64 = 0,
    metaDataLength: i32 = 0,
    bodyLength: i64 = 0,

    pub fn Pack(rcv: BlockT, __builder: *Builder, __pack_opts: fb.common.PackOptions) !u32 {
        _ = .{__pack_opts};
        return Block.Create(__builder, rcv.offset, rcv.metaDataLength, rcv.bodyLength);
    }
    pub fn UnpackTo(rcv: Block, t: *BlockT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.offset = rcv.Offset();
        t.metaDataLength = rcv.MetaDataLength();
        t.bodyLength = rcv.BodyLength();
    }

    pub fn Unpack(rcv: Block, __pack_opts: fb.common.PackOptions) !BlockT {
        var t = BlockT{};
        try BlockT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *BlockT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const Block = struct {
    _tab: fb.Struct,

    pub fn init(bytes: []u8, pos: u32) Block {
        return .{ ._tab = .{ ._tab = .{ .bytes = bytes, .pos = pos } } };
    }

    pub fn Table(x: Block) fb.Table {
        return x._tab._tab;
    }

    pub fn Offset(rcv: Block) i64 {
        return rcv._tab.read(i64, rcv._tab._tab.pos + 0);
    }
    pub fn MutateOffset(rcv: Block, n: i64) bool {
        return rcv._tab._tab.mutate(i64, rcv._tab._tab.pos + 0, n);
    }

    pub fn MetaDataLength(rcv: Block) i32 {
        return rcv._tab.read(i32, rcv._tab._tab.pos + 8);
    }
    pub fn MutateMetaDataLength(rcv: Block, n: i32) bool {
        return rcv._tab._tab.mutate(i32, rcv._tab._tab.pos + 8, n);
    }

    pub fn BodyLength(rcv: Block) i64 {
        return rcv._tab.read(i64, rcv._tab._tab.pos + 16);
    }
    pub fn MutateBodyLength(rcv: Block, n: i64) bool {
        return rcv._tab._tab.mutate(i64, rcv._tab._tab.pos + 16, n);
    }

    pub fn Create(__builder: *Builder, offset: i64, metaDataLength: i32, bodyLength: i64) !u32 {
        try __builder.prep(8, 24);
        try __builder.prepend(i64, bodyLength);
        __builder.pad(4);
        try __builder.prepend(i32, metaDataLength);
        try __builder.prepend(i64, offset);
        return __builder.offset();
    }
    pub fn Unpack(rcv: Block, __pack_opts: fb.common.PackOptions) !BlockT {
        return BlockT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = BlockT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = fb.GetRootAs(Block, bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
