//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Message.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Message.fbs
//! file ident: //Message.fbs
//! typename    org.apache.arrow.flatbuf.BodyCompression
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const BodyCompressionMethod = @import("BodyCompressionMethod.fb.zig").BodyCompressionMethod;
                const CompressionType = @import("CompressionType.fb.zig").CompressionType;
                const BodyCompression = @import("BodyCompression.fb.zig").BodyCompression;
                const BodyCompressionT = @import("BodyCompression.fb.zig").BodyCompressionT;
            };
        };
    };
};

/// Optional compression for the memory buffers constituting IPC message
/// bodies. Intended for use with RecordBatch but could be used for other
/// message types
pub const BodyCompressionT = struct {
    /// Compressor library.
    /// For LZ4_FRAME, each compressed buffer must consist of a single frame.
    codec: org.apache.arrow.flatbuf.CompressionType = @as(org.apache.arrow.flatbuf.CompressionType, @enumFromInt(0)),
    /// Indicates the way the record batch body was compressed
    method: org.apache.arrow.flatbuf.BodyCompressionMethod = @as(org.apache.arrow.flatbuf.BodyCompressionMethod, @enumFromInt(0)),

    pub fn Pack(rcv: BodyCompressionT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        try BodyCompression.Start(__builder);
        try BodyCompression.AddCodec(__builder, rcv.codec);
        try BodyCompression.AddMethod(__builder, rcv.method);
        return BodyCompression.End(__builder);
    }

    pub fn UnpackTo(rcv: BodyCompression, t: *BodyCompressionT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.codec = rcv.Codec();

        t.method = rcv.Method();
    }

    pub fn Unpack(rcv: BodyCompression, __pack_opts: fb.common.PackOptions) fb.common.PackError!BodyCompressionT {
        var t = BodyCompressionT{};
        try BodyCompressionT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *BodyCompressionT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const BodyCompression = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.BodyCompression {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.BodyCompression.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.BodyCompression {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.BodyCompression.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) BodyCompression {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: BodyCompression) fb.Table {
        return x._tab;
    }

    /// Compressor library.
    /// For LZ4_FRAME, each compressed buffer must consist of a single frame.
    pub fn Codec(rcv: BodyCompression) org.apache.arrow.flatbuf.CompressionType {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.CompressionType, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.CompressionType, @enumFromInt(0));
    }

    pub fn MutateCodec(rcv: BodyCompression, n: org.apache.arrow.flatbuf.CompressionType) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.CompressionType, 4, n);
    }

    /// Indicates the way the record batch body was compressed
    pub fn Method(rcv: BodyCompression) org.apache.arrow.flatbuf.BodyCompressionMethod {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.BodyCompressionMethod, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.BodyCompressionMethod, @enumFromInt(0));
    }

    pub fn MutateMethod(rcv: BodyCompression, n: org.apache.arrow.flatbuf.BodyCompressionMethod) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.BodyCompressionMethod, 6, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(2);
    }
    pub fn AddCodec(__builder: *Builder, codec: org.apache.arrow.flatbuf.CompressionType) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.CompressionType, 0, codec, @as(org.apache.arrow.flatbuf.CompressionType, @enumFromInt(0)));
    }

    pub fn AddMethod(__builder: *Builder, method: org.apache.arrow.flatbuf.BodyCompressionMethod) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.BodyCompressionMethod, 1, method, @as(org.apache.arrow.flatbuf.BodyCompressionMethod, @enumFromInt(0)));
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: BodyCompression, __pack_opts: fb.common.PackOptions) !BodyCompressionT {
        return BodyCompressionT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = BodyCompressionT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = BodyCompression.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
