//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Message.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Message.fbs
//! file ident: //Message.fbs
//! typename    org.apache.arrow.flatbuf.CompressionType
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const CompressionType = @import("CompressionType.fb.zig").CompressionType;
            };
        };
    };
};

pub const CompressionType = enum(i8) {
    LZ4_FRAME = 0,
    ZSTD = 1,
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};
