//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Date
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Date = @import("Date.fb.zig").Date;
                const DateT = @import("Date.fb.zig").DateT;
                const DateUnit = @import("DateUnit.fb.zig").DateUnit;
            };
        };
    };
};

/// Date is either a 32-bit or 64-bit signed integer type representing an
/// elapsed time since UNIX epoch (1970-01-01), stored in either of two units:
///
/// * Milliseconds (64 bits) indicating UNIX time elapsed since the epoch (no
///   leap seconds), where the values are evenly divisible by 86400000
/// * Days (32 bits) since the UNIX epoch
pub const DateT = struct {
    unit: org.apache.arrow.flatbuf.DateUnit = @as(org.apache.arrow.flatbuf.DateUnit, @enumFromInt(1)),

    pub fn Pack(rcv: DateT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        try Date.Start(__builder);
        try Date.AddUnit(__builder, rcv.unit);
        return Date.End(__builder);
    }

    pub fn UnpackTo(rcv: Date, t: *DateT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.unit = rcv.Unit();
    }

    pub fn Unpack(rcv: Date, __pack_opts: fb.common.PackOptions) fb.common.PackError!DateT {
        var t = DateT{};
        try DateT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *DateT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const Date = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Date {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Date.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Date {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Date.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Date {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Date) fb.Table {
        return x._tab;
    }

    pub fn Unit(rcv: Date) org.apache.arrow.flatbuf.DateUnit {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.DateUnit, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.DateUnit, @enumFromInt(1));
    }

    pub fn MutateUnit(rcv: Date, n: org.apache.arrow.flatbuf.DateUnit) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.DateUnit, 4, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(1);
    }
    pub fn AddUnit(__builder: *Builder, unit: org.apache.arrow.flatbuf.DateUnit) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.DateUnit, 0, unit, @as(org.apache.arrow.flatbuf.DateUnit, @enumFromInt(1)));
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Date, __pack_opts: fb.common.PackOptions) !DateT {
        return DateT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = DateT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Date.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
