//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.DictionaryEncoding
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const DictionaryKind = @import("DictionaryKind.fb.zig").DictionaryKind;
                const Int = @import("Int.fb.zig").Int;
                const IntT = @import("Int.fb.zig").IntT;
                const DictionaryEncoding = @import("DictionaryEncoding.fb.zig").DictionaryEncoding;
                const DictionaryEncodingT = @import("DictionaryEncoding.fb.zig").DictionaryEncodingT;
            };
        };
    };
};

pub const DictionaryEncodingT = struct {
    /// The known dictionary id in the application where this data is used. In
    /// the file or streaming formats, the dictionary ids are found in the
    /// DictionaryBatch messages
    id: i64 = 0,
    /// The dictionary indices are constrained to be non-negative integers. If
    /// this field is null, the indices must be signed int32. To maximize
    /// cross-language compatibility and performance, implementations are
    /// recommended to prefer signed integer types over unsigned integer types
    /// and to avoid uint64 indices unless they are required by an application.
    indexType: ?*org.apache.arrow.flatbuf.IntT = null,
    /// By default, dictionaries are not ordered, or the order does not have
    /// semantic meaning. In some statistical applications, dictionary-encoding
    /// is used to represent ordered categorical data, and we provide a way to
    /// preserve that metadata here
    isOrdered: bool = false,
    dictionaryKind: org.apache.arrow.flatbuf.DictionaryKind = @as(org.apache.arrow.flatbuf.DictionaryKind, @enumFromInt(0)),

    pub fn Pack(rcv: DictionaryEncodingT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const indexType_off = if (rcv.indexType) |x| try x.Pack(__builder, __pack_opts) else 0;

        try DictionaryEncoding.Start(__builder);
        try DictionaryEncoding.AddId(__builder, rcv.id);
        try DictionaryEncoding.AddIndexType(__builder, indexType_off);
        try DictionaryEncoding.AddIsOrdered(__builder, rcv.isOrdered);
        try DictionaryEncoding.AddDictionaryKind(__builder, rcv.dictionaryKind);
        return DictionaryEncoding.End(__builder);
    }

    pub fn UnpackTo(rcv: DictionaryEncoding, t: *DictionaryEncodingT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.id = rcv.Id();

        if (rcv.IndexType()) |x| {
            if (t.indexType == null) {
                t.indexType = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                t.indexType.?.* = .{};
            }
            try org.apache.arrow.flatbuf.IntT.UnpackTo(x, t.indexType.?, __pack_opts);
        }

        t.isOrdered = rcv.IsOrdered();

        t.dictionaryKind = rcv.DictionaryKind();
    }

    pub fn Unpack(rcv: DictionaryEncoding, __pack_opts: fb.common.PackOptions) fb.common.PackError!DictionaryEncodingT {
        var t = DictionaryEncodingT{};
        try DictionaryEncodingT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *DictionaryEncodingT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        if (self.indexType) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
    }
};

pub const DictionaryEncoding = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.DictionaryEncoding {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.DictionaryEncoding.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.DictionaryEncoding {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.DictionaryEncoding.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) DictionaryEncoding {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: DictionaryEncoding) fb.Table {
        return x._tab;
    }

    /// The known dictionary id in the application where this data is used. In
    /// the file or streaming formats, the dictionary ids are found in the
    /// DictionaryBatch messages
    pub fn Id(rcv: DictionaryEncoding) i64 {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(i64, o + rcv._tab.pos);
        }
        return 0;
    }

    pub fn MutateId(rcv: DictionaryEncoding, n: i64) bool {
        return rcv._tab.mutateSlot(i64, 4, n);
    }

    /// The dictionary indices are constrained to be non-negative integers. If
    /// this field is null, the indices must be signed int32. To maximize
    /// cross-language compatibility and performance, implementations are
    /// recommended to prefer signed integer types over unsigned integer types
    /// and to avoid uint64 indices unless they are required by an application.
    pub fn IndexType(rcv: DictionaryEncoding) ?org.apache.arrow.flatbuf.Int {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.Int.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// By default, dictionaries are not ordered, or the order does not have
    /// semantic meaning. In some statistical applications, dictionary-encoding
    /// is used to represent ordered categorical data, and we provide a way to
    /// preserve that metadata here
    pub fn IsOrdered(rcv: DictionaryEncoding) bool {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            return rcv._tab.read(bool, o + rcv._tab.pos);
        }
        return false;
    }

    pub fn MutateIsOrdered(rcv: DictionaryEncoding, n: bool) bool {
        return rcv._tab.mutateSlot(bool, 8, n);
    }

    pub fn DictionaryKind(rcv: DictionaryEncoding) org.apache.arrow.flatbuf.DictionaryKind {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.DictionaryKind, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.DictionaryKind, @enumFromInt(0));
    }

    pub fn MutateDictionaryKind(rcv: DictionaryEncoding, n: org.apache.arrow.flatbuf.DictionaryKind) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.DictionaryKind, 10, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(4);
    }
    pub fn AddId(__builder: *Builder, id: i64) !void {
        try __builder.prependSlot(i64, 0, id, 0);
    }

    pub fn AddIndexType(__builder: *Builder, indexType: u32) !void {
        try __builder.prependSlotUOff(1, indexType, 0);
    }

    pub fn AddIsOrdered(__builder: *Builder, isOrdered: bool) !void {
        try __builder.prependSlot(bool, 2, isOrdered, false);
    }

    pub fn AddDictionaryKind(__builder: *Builder, dictionaryKind: org.apache.arrow.flatbuf.DictionaryKind) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.DictionaryKind, 3, dictionaryKind, @as(org.apache.arrow.flatbuf.DictionaryKind, @enumFromInt(0)));
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: DictionaryEncoding, __pack_opts: fb.common.PackOptions) !DictionaryEncodingT {
        return DictionaryEncodingT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = DictionaryEncodingT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = DictionaryEncoding.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
