//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Duration
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Duration = @import("Duration.fb.zig").Duration;
                const DurationT = @import("Duration.fb.zig").DurationT;
                const TimeUnit = @import("TimeUnit.fb.zig").TimeUnit;
            };
        };
    };
};

pub const DurationT = struct {
    unit: org.apache.arrow.flatbuf.TimeUnit = @as(org.apache.arrow.flatbuf.TimeUnit, @enumFromInt(1)),

    pub fn Pack(rcv: DurationT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        try Duration.Start(__builder);
        try Duration.AddUnit(__builder, rcv.unit);
        return Duration.End(__builder);
    }

    pub fn UnpackTo(rcv: Duration, t: *DurationT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.unit = rcv.Unit();
    }

    pub fn Unpack(rcv: Duration, __pack_opts: fb.common.PackOptions) fb.common.PackError!DurationT {
        var t = DurationT{};
        try DurationT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *DurationT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const Duration = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Duration {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Duration.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Duration {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Duration.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Duration {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Duration) fb.Table {
        return x._tab;
    }

    pub fn Unit(rcv: Duration) org.apache.arrow.flatbuf.TimeUnit {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.TimeUnit, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.TimeUnit, @enumFromInt(1));
    }

    pub fn MutateUnit(rcv: Duration, n: org.apache.arrow.flatbuf.TimeUnit) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.TimeUnit, 4, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(1);
    }
    pub fn AddUnit(__builder: *Builder, unit: org.apache.arrow.flatbuf.TimeUnit) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.TimeUnit, 0, unit, @as(org.apache.arrow.flatbuf.TimeUnit, @enumFromInt(1)));
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Duration, __pack_opts: fb.common.PackOptions) !DurationT {
        return DurationT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = DurationT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Duration.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
