//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Endianness
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Endianness = @import("Endianness.fb.zig").Endianness;
            };
        };
    };
};

/// ----------------------------------------------------------------------
/// Endianness of the platform producing the data
pub const Endianness = enum(i16) {
    Little = 0,
    Big = 1,
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};
