//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Field
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Type = @import("Type.fb.zig").Type;
                const TypeT = @import("Type.fb.zig").TypeT;
                const KeyValue = @import("KeyValue.fb.zig").KeyValue;
                const KeyValueT = @import("KeyValue.fb.zig").KeyValueT;
                const Field = @import("Field.fb.zig").Field;
                const FieldT = @import("Field.fb.zig").FieldT;
                const DictionaryEncoding = @import("DictionaryEncoding.fb.zig").DictionaryEncoding;
                const DictionaryEncodingT = @import("DictionaryEncoding.fb.zig").DictionaryEncodingT;
            };
        };
    };
};

/// ----------------------------------------------------------------------
/// A field represents a named column in a record / row batch or child of a
/// nested type.
pub const FieldT = struct {
    /// Name is not required (e.g., in a List)
    name: []const u8 = "",
    /// Whether or not this field can contain nulls. Should be true in general.
    nullable: bool = false,
    /// This is the type of the decoded value if the field is dictionary encoded.
    type: org.apache.arrow.flatbuf.TypeT = @as(org.apache.arrow.flatbuf.Type.Tag, @enumFromInt(0)),
    /// Present only if the field is dictionary encoded.
    dictionary: ?*org.apache.arrow.flatbuf.DictionaryEncodingT = null,
    /// children apply only to nested data types like Struct, List and Union. For
    /// primitive types children will have length 0.
    children: std.ArrayList(org.apache.arrow.flatbuf.FieldT) = .{},
    /// User-defined metadata
    custom_metadata: std.ArrayList(org.apache.arrow.flatbuf.KeyValueT) = .{},

    pub fn Pack(rcv: FieldT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const name_off = if (rcv.name.len != 0) try __builder.createString(rcv.name) else 0;

        const type_off = try rcv.type.Pack(__builder, __pack_opts);

        const dictionary_off = if (rcv.dictionary) |x| try x.Pack(__builder, __pack_opts) else 0;

        var children_off: u32 = 0;
        if (rcv.children.items.len != 0) {
            const children_len: i32 = @intCast(rcv.children.items.len);
            try __tmp_offsets.ensureTotalCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(children_len)));
            __tmp_offsets.items.len = @as(u32, @bitCast(children_len));
            for (__tmp_offsets.items, 0..) |*off, j| {
                off.* = try org.apache.arrow.flatbuf.FieldT.Pack(rcv.children.items[j], __builder, __pack_opts);
            }
            _ = try Field.StartChildrenVector(__builder, children_len);
            {
                var j = children_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prependUOff(__tmp_offsets.items[@as(u32, @bitCast(j))]);
                }
                children_off = try __builder.endVector(@bitCast(children_len));
            }
        }

        var custom_metadata_off: u32 = 0;
        if (rcv.custom_metadata.items.len != 0) {
            const custom_metadata_len: i32 = @intCast(rcv.custom_metadata.items.len);
            try __tmp_offsets.ensureTotalCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(custom_metadata_len)));
            __tmp_offsets.items.len = @as(u32, @bitCast(custom_metadata_len));
            for (__tmp_offsets.items, 0..) |*off, j| {
                off.* = try org.apache.arrow.flatbuf.KeyValueT.Pack(rcv.custom_metadata.items[j], __builder, __pack_opts);
            }
            _ = try Field.StartCustomMetadataVector(__builder, custom_metadata_len);
            {
                var j = custom_metadata_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prependUOff(__tmp_offsets.items[@as(u32, @bitCast(j))]);
                }
                custom_metadata_off = try __builder.endVector(@bitCast(custom_metadata_len));
            }
        }

        try Field.Start(__builder);
        try Field.AddName(__builder, name_off);
        try Field.AddNullable(__builder, rcv.nullable);
        try Field.AddTypeType(__builder, rcv.type);
        try Field.AddType(__builder, type_off);
        try Field.AddDictionary(__builder, dictionary_off);
        try Field.AddChildren(__builder, children_off);
        try Field.AddCustomMetadata(__builder, custom_metadata_off);
        return Field.End(__builder);
    }

    pub fn UnpackTo(rcv: Field, t: *FieldT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.name = rcv.Name();

        t.nullable = rcv.Nullable();

        if (rcv.Type()) |_tab| {
            t.type = try org.apache.arrow.flatbuf.TypeT.Unpack(rcv.TypeType(), _tab, __pack_opts);
        }

        if (rcv.Dictionary()) |x| {
            if (t.dictionary == null) {
                t.dictionary = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.DictionaryEncodingT);
                t.dictionary.?.* = .{};
            }
            try org.apache.arrow.flatbuf.DictionaryEncodingT.UnpackTo(x, t.dictionary.?, __pack_opts);
        }

        const children_len = rcv.ChildrenLen();
        t.children = try std.ArrayList(org.apache.arrow.flatbuf.FieldT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(children_len)));
        t.children.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < children_len) : (j += 1) {
                const x = rcv.Children(j).?;
                t.children.items[j] = try x.Unpack(__pack_opts);
            }
        }

        const custom_metadata_len = rcv.CustomMetadataLen();
        t.custom_metadata = try std.ArrayList(org.apache.arrow.flatbuf.KeyValueT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(custom_metadata_len)));
        t.custom_metadata.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < custom_metadata_len) : (j += 1) {
                const x = rcv.CustomMetadata(j).?;
                t.custom_metadata.items[j] = try x.Unpack(__pack_opts);
            }
        }
    }

    pub fn Unpack(rcv: Field, __pack_opts: fb.common.PackOptions) fb.common.PackError!FieldT {
        var t = FieldT{};
        try FieldT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *FieldT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        // TODO __pack_opts.dupe_strings
        // if(self.name.len > 0) allocator.free(self.name);
        self.type.deinit(allocator);
        if (self.dictionary) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        for (self.children.items) |*it| it.deinit(allocator);
        self.children.deinit(allocator);
        for (self.custom_metadata.items) |*it| it.deinit(allocator);
        self.custom_metadata.deinit(allocator);
    }
};

pub const Field = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Field {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Field.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Field {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Field.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Field {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Field) fb.Table {
        return x._tab;
    }

    /// Name is not required (e.g., in a List)
    pub fn Name(rcv: Field) []const u8 {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    /// Whether or not this field can contain nulls. Should be true in general.
    pub fn Nullable(rcv: Field) bool {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.read(bool, o + rcv._tab.pos);
        }
        return false;
    }

    pub fn MutateNullable(rcv: Field, n: bool) bool {
        return rcv._tab.mutateSlot(bool, 6, n);
    }

    pub fn TypeType(rcv: Field) org.apache.arrow.flatbuf.Type.Tag {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.Type.Tag, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.Type.Tag, @enumFromInt(0));
    }

    pub fn MutateTypeType(rcv: Field, n: org.apache.arrow.flatbuf.Type) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.Type, 8, n);
    }

    /// This is the type of the decoded value if the field is dictionary encoded.
    pub fn Type(rcv: Field) ?fb.Table {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.union_(o);
        }
        return null;
    }

    /// Present only if the field is dictionary encoded.
    pub fn Dictionary(rcv: Field) ?org.apache.arrow.flatbuf.DictionaryEncoding {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.DictionaryEncoding.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// children apply only to nested data types like Struct, List and Union. For
    /// primitive types children will have length 0.
    pub fn Children(rcv: Field, j: usize) ?org.apache.arrow.flatbuf.Field {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return org.apache.arrow.flatbuf.Field.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn ChildrenLen(rcv: Field) u32 {
        const o = rcv._tab.offset(14);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// User-defined metadata
    pub fn CustomMetadata(rcv: Field, j: usize) ?org.apache.arrow.flatbuf.KeyValue {
        const o = rcv._tab.offset(16);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return org.apache.arrow.flatbuf.KeyValue.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn CustomMetadataLen(rcv: Field) u32 {
        const o = rcv._tab.offset(16);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(7);
    }
    pub fn AddName(__builder: *Builder, name: u32) !void {
        try __builder.prependSlotUOff(0, name, 0);
    }

    pub fn AddNullable(__builder: *Builder, nullable: bool) !void {
        try __builder.prependSlot(bool, 1, nullable, false);
    }

    pub fn AddTypeType(__builder: *Builder, type_type: org.apache.arrow.flatbuf.Type.Tag) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.Type.Tag, 2, type_type, @as(org.apache.arrow.flatbuf.Type.Tag, @enumFromInt(0)));
    }

    pub fn AddType(__builder: *Builder, @"type": u32) !void {
        try __builder.prependSlotUOff(3, @"type", 0);
    }

    pub fn AddDictionary(__builder: *Builder, dictionary: u32) !void {
        try __builder.prependSlotUOff(4, dictionary, 0);
    }

    pub fn AddChildren(__builder: *Builder, children: u32) !void {
        try __builder.prependSlotUOff(5, children, 0);
    }

    pub fn StartChildrenVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddCustomMetadata(__builder: *Builder, custom_metadata: u32) !void {
        try __builder.prependSlotUOff(6, custom_metadata, 0);
    }

    pub fn StartCustomMetadataVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Field, __pack_opts: fb.common.PackOptions) !FieldT {
        return FieldT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = FieldT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Field.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
