//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.FloatingPoint
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Precision = @import("Precision.fb.zig").Precision;
                const FloatingPoint = @import("FloatingPoint.fb.zig").FloatingPoint;
                const FloatingPointT = @import("FloatingPoint.fb.zig").FloatingPointT;
            };
        };
    };
};

pub const FloatingPointT = struct {
    precision: org.apache.arrow.flatbuf.Precision = @as(org.apache.arrow.flatbuf.Precision, @enumFromInt(0)),

    pub fn Pack(rcv: FloatingPointT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        try FloatingPoint.Start(__builder);
        try FloatingPoint.AddPrecision(__builder, rcv.precision);
        return FloatingPoint.End(__builder);
    }

    pub fn UnpackTo(rcv: FloatingPoint, t: *FloatingPointT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.precision = rcv.Precision();
    }

    pub fn Unpack(rcv: FloatingPoint, __pack_opts: fb.common.PackOptions) fb.common.PackError!FloatingPointT {
        var t = FloatingPointT{};
        try FloatingPointT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *FloatingPointT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const FloatingPoint = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.FloatingPoint {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.FloatingPoint.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.FloatingPoint {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.FloatingPoint.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) FloatingPoint {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: FloatingPoint) fb.Table {
        return x._tab;
    }

    pub fn Precision(rcv: FloatingPoint) org.apache.arrow.flatbuf.Precision {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.Precision, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.Precision, @enumFromInt(0));
    }

    pub fn MutatePrecision(rcv: FloatingPoint, n: org.apache.arrow.flatbuf.Precision) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.Precision, 4, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(1);
    }
    pub fn AddPrecision(__builder: *Builder, precision: org.apache.arrow.flatbuf.Precision) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.Precision, 0, precision, @as(org.apache.arrow.flatbuf.Precision, @enumFromInt(0)));
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: FloatingPoint, __pack_opts: fb.common.PackOptions) !FloatingPointT {
        return FloatingPointT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = FloatingPointT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = FloatingPoint.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
