//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Interval
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const IntervalUnit = @import("IntervalUnit.fb.zig").IntervalUnit;
                const Interval = @import("Interval.fb.zig").Interval;
                const IntervalT = @import("Interval.fb.zig").IntervalT;
            };
        };
    };
};

pub const IntervalT = struct {
    unit: org.apache.arrow.flatbuf.IntervalUnit = @as(org.apache.arrow.flatbuf.IntervalUnit, @enumFromInt(0)),

    pub fn Pack(rcv: IntervalT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        try Interval.Start(__builder);
        try Interval.AddUnit(__builder, rcv.unit);
        return Interval.End(__builder);
    }

    pub fn UnpackTo(rcv: Interval, t: *IntervalT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.unit = rcv.Unit();
    }

    pub fn Unpack(rcv: Interval, __pack_opts: fb.common.PackOptions) fb.common.PackError!IntervalT {
        var t = IntervalT{};
        try IntervalT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *IntervalT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const Interval = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Interval {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Interval.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Interval {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Interval.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Interval {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Interval) fb.Table {
        return x._tab;
    }

    pub fn Unit(rcv: Interval) org.apache.arrow.flatbuf.IntervalUnit {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.IntervalUnit, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.IntervalUnit, @enumFromInt(0));
    }

    pub fn MutateUnit(rcv: Interval, n: org.apache.arrow.flatbuf.IntervalUnit) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.IntervalUnit, 4, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(1);
    }
    pub fn AddUnit(__builder: *Builder, unit: org.apache.arrow.flatbuf.IntervalUnit) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.IntervalUnit, 0, unit, @as(org.apache.arrow.flatbuf.IntervalUnit, @enumFromInt(0)));
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Interval, __pack_opts: fb.common.PackOptions) !IntervalT {
        return IntervalT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = IntervalT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Interval.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
