//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Message.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Message.fbs
//! file ident: //Message.fbs
//! typename    org.apache.arrow.flatbuf.MessageHeader
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const SparseTensor = @import("SparseTensor.fb.zig").SparseTensor;
                const SparseTensorT = @import("SparseTensor.fb.zig").SparseTensorT;
                const RecordBatch = @import("RecordBatch.fb.zig").RecordBatch;
                const RecordBatchT = @import("RecordBatch.fb.zig").RecordBatchT;
                const Tensor = @import("Tensor.fb.zig").Tensor;
                const TensorT = @import("Tensor.fb.zig").TensorT;
                const DictionaryBatch = @import("DictionaryBatch.fb.zig").DictionaryBatch;
                const DictionaryBatchT = @import("DictionaryBatch.fb.zig").DictionaryBatchT;
                const Schema = @import("Schema.fb.zig").Schema;
                const SchemaT = @import("Schema.fb.zig").SchemaT;
                const MessageHeader = @import("MessageHeader.fb.zig").MessageHeader;
            };
        };
    };
};

/// ----------------------------------------------------------------------
/// The root Message type
/// This union enables us to easily send different message types without
/// redundant storage, and in the future we can easily add new message types.
///
/// Arrow implementations do not need to implement all of the message types,
/// which may include experimental metadata types. For maximum compatibility,
/// it is best to send data using RecordBatch
pub const MessageHeader = union(enum) {
    NONE,
    Schema: org.apache.arrow.flatbuf.Schema,
    DictionaryBatch: org.apache.arrow.flatbuf.DictionaryBatch,
    RecordBatch: org.apache.arrow.flatbuf.RecordBatch,
    Tensor: org.apache.arrow.flatbuf.Tensor,
    SparseTensor: org.apache.arrow.flatbuf.SparseTensor,

    pub const Tag = std.meta.Tag(@This());
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};

pub const MessageHeaderT = union(MessageHeader.Tag) {
    NONE: void,
    Schema: ?*org.apache.arrow.flatbuf.SchemaT,
    DictionaryBatch: ?*org.apache.arrow.flatbuf.DictionaryBatchT,
    RecordBatch: ?*org.apache.arrow.flatbuf.RecordBatchT,
    Tensor: ?*org.apache.arrow.flatbuf.TensorT,
    SparseTensor: ?*org.apache.arrow.flatbuf.SparseTensorT,

    pub fn deinit(self: *MessageHeaderT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        switch (self.*) {
            .NONE => {},
            .Schema => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Schema = null;
            },
            .DictionaryBatch => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.DictionaryBatch = null;
            },
            .RecordBatch => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.RecordBatch = null;
            },
            .Tensor => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Tensor = null;
            },
            .SparseTensor => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.SparseTensor = null;
            },
        }
    }

    pub fn Pack(rcv: MessageHeaderT, __builder: *Builder, __pack_opts: fb.common.PackOptions) !u32 {
        _ = .{ __builder, __pack_opts };
        // std.debug.print("pack() MessageHeaderT rcv=.{s}\n", .{@tagName(rcv)});
        switch (rcv) {
            .NONE => {},
            .Schema => |x| return x.?.Pack(__builder, __pack_opts),
            .DictionaryBatch => |x| return x.?.Pack(__builder, __pack_opts),
            .RecordBatch => |x| return x.?.Pack(__builder, __pack_opts),
            .Tensor => |x| return x.?.Pack(__builder, __pack_opts),
            .SparseTensor => |x| return x.?.Pack(__builder, __pack_opts),
        }
        return 0;
    }

    pub fn Unpack(rcv: MessageHeader.Tag, table: fb.Table, __pack_opts: fb.common.PackOptions) !MessageHeaderT {
        _ = .{ table, __pack_opts };
        // std.debug.print("unpack() MessageHeader rcv=.{s}\n", .{@tagName(rcv)});
        switch (rcv) {
            .NONE => return .NONE,
            .Schema => {
                const x = org.apache.arrow.flatbuf.Schema.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.SchemaT);
                ptr.* = try org.apache.arrow.flatbuf.SchemaT.Unpack(x, __pack_opts);
                return .{ .Schema = ptr };
            },
            .DictionaryBatch => {
                const x = org.apache.arrow.flatbuf.DictionaryBatch.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.DictionaryBatchT);
                ptr.* = try org.apache.arrow.flatbuf.DictionaryBatchT.Unpack(x, __pack_opts);
                return .{ .DictionaryBatch = ptr };
            },
            .RecordBatch => {
                const x = org.apache.arrow.flatbuf.RecordBatch.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.RecordBatchT);
                ptr.* = try org.apache.arrow.flatbuf.RecordBatchT.Unpack(x, __pack_opts);
                return .{ .RecordBatch = ptr };
            },
            .Tensor => {
                const x = org.apache.arrow.flatbuf.Tensor.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.TensorT);
                ptr.* = try org.apache.arrow.flatbuf.TensorT.Unpack(x, __pack_opts);
                return .{ .Tensor = ptr };
            },
            .SparseTensor => {
                const x = org.apache.arrow.flatbuf.SparseTensor.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.SparseTensorT);
                ptr.* = try org.apache.arrow.flatbuf.SparseTensorT.Unpack(x, __pack_opts);
                return .{ .SparseTensor = ptr };
            },
        }
        unreachable;
    }
};

test {
    var obj: MessageHeaderT = .NONE;
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    const table = fb.Table.init(bytes, 0);
    const obj2 = try MessageHeaderT.Unpack(.NONE, table, opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
