//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Precision
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Precision = @import("Precision.fb.zig").Precision;
            };
        };
    };
};

pub const Precision = enum(i16) {
    HALF = 0,
    SINGLE = 1,
    DOUBLE = 2,
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};
