//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Schema
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Endianness = @import("Endianness.fb.zig").Endianness;
                const KeyValue = @import("KeyValue.fb.zig").KeyValue;
                const KeyValueT = @import("KeyValue.fb.zig").KeyValueT;
                const Schema = @import("Schema.fb.zig").Schema;
                const SchemaT = @import("Schema.fb.zig").SchemaT;
                const Field = @import("Field.fb.zig").Field;
                const FieldT = @import("Field.fb.zig").FieldT;
            };
        };
    };
};

pub const __file_ident: fb.Builder.Fid = "".*;
pub const __file_ext = "";

/// ----------------------------------------------------------------------
/// A Schema describes the columns in a row batch
pub const SchemaT = struct {
    /// endianness of the buffer
    /// it is Little Endian by default
    /// if endianness doesn't match the underlying system then the vectors need to be converted
    endianness: org.apache.arrow.flatbuf.Endianness = @as(org.apache.arrow.flatbuf.Endianness, @enumFromInt(0)),
    fields: std.ArrayList(org.apache.arrow.flatbuf.FieldT) = .{},
    custom_metadata: std.ArrayList(org.apache.arrow.flatbuf.KeyValueT) = .{},
    /// Features used in the stream/file.
    features: std.ArrayList(i64) = .{},

    pub fn Pack(rcv: SchemaT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        var fields_off: u32 = 0;
        if (rcv.fields.items.len != 0) {
            const fields_len: i32 = @intCast(rcv.fields.items.len);
            try __tmp_offsets.ensureTotalCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(fields_len)));
            __tmp_offsets.items.len = @as(u32, @bitCast(fields_len));
            for (__tmp_offsets.items, 0..) |*off, j| {
                off.* = try org.apache.arrow.flatbuf.FieldT.Pack(rcv.fields.items[j], __builder, __pack_opts);
            }
            _ = try Schema.StartFieldsVector(__builder, fields_len);
            {
                var j = fields_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prependUOff(__tmp_offsets.items[@as(u32, @bitCast(j))]);
                }
                fields_off = try __builder.endVector(@bitCast(fields_len));
            }
        }

        var custom_metadata_off: u32 = 0;
        if (rcv.custom_metadata.items.len != 0) {
            const custom_metadata_len: i32 = @intCast(rcv.custom_metadata.items.len);
            try __tmp_offsets.ensureTotalCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(custom_metadata_len)));
            __tmp_offsets.items.len = @as(u32, @bitCast(custom_metadata_len));
            for (__tmp_offsets.items, 0..) |*off, j| {
                off.* = try org.apache.arrow.flatbuf.KeyValueT.Pack(rcv.custom_metadata.items[j], __builder, __pack_opts);
            }
            _ = try Schema.StartCustomMetadataVector(__builder, custom_metadata_len);
            {
                var j = custom_metadata_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prependUOff(__tmp_offsets.items[@as(u32, @bitCast(j))]);
                }
                custom_metadata_off = try __builder.endVector(@bitCast(custom_metadata_len));
            }
        }

        var features_off: u32 = 0;
        if (rcv.features.items.len != 0) {
            const features_len: i32 = @intCast(rcv.features.items.len);
            _ = try Schema.StartFeaturesVector(__builder, features_len);
            {
                var j = features_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prepend(i64, rcv.features.items[@as(u32, @bitCast(j))]);
                }
                features_off = try __builder.endVector(@bitCast(features_len));
            }
        }

        try Schema.Start(__builder);
        try Schema.AddEndianness(__builder, rcv.endianness);
        try Schema.AddFields(__builder, fields_off);
        try Schema.AddCustomMetadata(__builder, custom_metadata_off);
        try Schema.AddFeatures(__builder, features_off);
        return Schema.End(__builder);
    }

    pub fn UnpackTo(rcv: Schema, t: *SchemaT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.endianness = rcv.Endianness();

        const fields_len = rcv.FieldsLen();
        t.fields = try std.ArrayList(org.apache.arrow.flatbuf.FieldT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(fields_len)));
        t.fields.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < fields_len) : (j += 1) {
                const x = rcv.Fields(j).?;
                t.fields.items[j] = try x.Unpack(__pack_opts);
            }
        }

        const custom_metadata_len = rcv.CustomMetadataLen();
        t.custom_metadata = try std.ArrayList(org.apache.arrow.flatbuf.KeyValueT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(custom_metadata_len)));
        t.custom_metadata.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < custom_metadata_len) : (j += 1) {
                const x = rcv.CustomMetadata(j).?;
                t.custom_metadata.items[j] = try x.Unpack(__pack_opts);
            }
        }

        const features_len = rcv.FeaturesLen();
        t.features = try std.ArrayList(i64).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(features_len)));
        t.features.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < features_len) : (j += 1) {
                t.features.items[j] = rcv.Features(j).?;
            }
        }
    }

    pub fn Unpack(rcv: Schema, __pack_opts: fb.common.PackOptions) fb.common.PackError!SchemaT {
        var t = SchemaT{};
        try SchemaT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *SchemaT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        for (self.fields.items) |*it| it.deinit(allocator);
        self.fields.deinit(allocator);
        for (self.custom_metadata.items) |*it| it.deinit(allocator);
        self.custom_metadata.deinit(allocator);
        self.features.deinit(allocator);
    }
};

pub const Schema = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Schema {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Schema.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Schema {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Schema.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Schema {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Schema) fb.Table {
        return x._tab;
    }

    /// endianness of the buffer
    /// it is Little Endian by default
    /// if endianness doesn't match the underlying system then the vectors need to be converted
    pub fn Endianness(rcv: Schema) org.apache.arrow.flatbuf.Endianness {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.Endianness, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.Endianness, @enumFromInt(0));
    }

    pub fn MutateEndianness(rcv: Schema, n: org.apache.arrow.flatbuf.Endianness) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.Endianness, 4, n);
    }

    pub fn Fields(rcv: Schema, j: usize) ?org.apache.arrow.flatbuf.Field {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return org.apache.arrow.flatbuf.Field.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn FieldsLen(rcv: Schema) u32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn CustomMetadata(rcv: Schema, j: usize) ?org.apache.arrow.flatbuf.KeyValue {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return org.apache.arrow.flatbuf.KeyValue.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn CustomMetadataLen(rcv: Schema) u32 {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// Features used in the stream/file.
    pub fn Features(rcv: Schema, j: usize) ?i64 {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.read(i64, a + @as(u32, @intCast(j)) * 8);
        }
        return 0;
    }

    pub fn FeaturesLen(rcv: Schema) u32 {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn MutateFeatures(rcv: Schema, j: usize, n: i64) bool {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.mutate(i64, a + @as(u32, @intCast(j)) * 8, n);
        }
        return false;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(4);
    }
    pub fn AddEndianness(__builder: *Builder, endianness: org.apache.arrow.flatbuf.Endianness) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.Endianness, 0, endianness, @as(org.apache.arrow.flatbuf.Endianness, @enumFromInt(0)));
    }

    pub fn AddFields(__builder: *Builder, fields: u32) !void {
        try __builder.prependSlotUOff(1, fields, 0);
    }

    pub fn StartFieldsVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddCustomMetadata(__builder: *Builder, custom_metadata: u32) !void {
        try __builder.prependSlotUOff(2, custom_metadata, 0);
    }

    pub fn StartCustomMetadataVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddFeatures(__builder: *Builder, features: u32) !void {
        try __builder.prependSlotUOff(3, features, 0);
    }

    pub fn StartFeaturesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(8, num_elems, 8);
    }
    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Schema, __pack_opts: fb.common.PackOptions) !SchemaT {
        return SchemaT.Unpack(rcv, __pack_opts);
    }
    pub fn BufferHasIdentifier(buf: []const u8, off: u32) bool {
        return fb.BufferHasIdentifier(buf, off, __file_ident, false);
    }

    pub fn SizePrefixedBufferHasIdentifier(buf: []const u8, off: u32) bool {
        return fb.BufferHasIdentifier(buf, off, __file_ident, true);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.finishWithFileIdentifier(root, __file_ident);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.finishSizePrefixedWithFileIdentifier(root, __file_ident);
    }
};

test {
    var obj = SchemaT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Schema.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
