//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.fbs
//! file ident: //SparseTensor.fbs
//! typename    org.apache.arrow.flatbuf.SparseMatrixCompressedAxis
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const SparseMatrixCompressedAxis = @import("SparseMatrixCompressedAxis.fb.zig").SparseMatrixCompressedAxis;
            };
        };
    };
};

pub const SparseMatrixCompressedAxis = enum(i16) {
    Row = 0,
    Column = 1,
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};
