//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.fbs
//! file ident: //SparseTensor.fbs
//! typename    org.apache.arrow.flatbuf.SparseTensorIndexCOO
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const SparseTensorIndexCOO = @import("SparseTensorIndexCOO.fb.zig").SparseTensorIndexCOO;
                const SparseTensorIndexCOOT = @import("SparseTensorIndexCOO.fb.zig").SparseTensorIndexCOOT;
                const Int = @import("Int.fb.zig").Int;
                const IntT = @import("Int.fb.zig").IntT;
                const Buffer = @import("Buffer.fb.zig").Buffer;
                const BufferT = @import("Buffer.fb.zig").BufferT;
            };
        };
    };
};

/// ----------------------------------------------------------------------
/// EXPERIMENTAL: Data structures for sparse tensors
/// Coordinate (COO) format of sparse tensor index.
///
/// COO's index list is represented as an NxM matrix,
/// where N is the number of non-zero values,
/// and M is the number of dimensions of a sparse tensor.
///
/// indicesBuffer stores the location and size of the data of these indices
/// matrix.  The value type and the stride of the indices matrix is
/// specified in indicesType and indicesStrides fields.
///
/// For example, let X be a 2x3x4x5 tensor, and it has the following
/// 6 non-zero values:
/// ```text
///   X[0, 1, 2, 0] := 1
///   X[1, 1, 2, 3] := 2
///   X[0, 2, 1, 0] := 3
///   X[0, 1, 3, 0] := 4
///   X[0, 1, 2, 1] := 5
///   X[1, 2, 0, 4] := 6
/// ```
/// In COO format, the index matrix of X is the following 4x6 matrix:
/// ```text
///   [[0, 0, 0, 0, 1, 1],
///    [1, 1, 1, 2, 1, 2],
///    [2, 2, 3, 1, 2, 0],
///    [0, 1, 0, 0, 3, 4]]
/// ```
/// When isCanonical is true, the indices are sorted in lexicographical order
/// (row-major order), and it does not have duplicated entries.  Otherwise,
/// the indices may not be sorted, or may have duplicated entries.
pub const SparseTensorIndexCOOT = struct {
    /// The type of values in indicesBuffer
    indicesType: ?*org.apache.arrow.flatbuf.IntT = null,
    /// Non-negative byte offsets to advance one value cell along each dimension
    /// If omitted, default to row-major order (C-like).
    indicesStrides: std.ArrayList(i64) = .{},
    /// The location and size of the indices matrix's data
    indicesBuffer: ?*org.apache.arrow.flatbuf.BufferT = null,
    /// This flag is true if and only if the indices matrix is sorted in
    /// row-major order, and does not have duplicated entries.
    /// This sort order is the same as of Tensorflow's SparseTensor,
    /// but it is inverse order of SciPy's canonical coo_matrix
    /// (SciPy employs column-major order for its coo_matrix).
    isCanonical: bool = false,

    pub fn Pack(rcv: SparseTensorIndexCOOT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const indicesType_off = if (rcv.indicesType) |x| try x.Pack(__builder, __pack_opts) else 0;

        var indicesStrides_off: u32 = 0;
        if (rcv.indicesStrides.items.len != 0) {
            const indicesStrides_len: i32 = @intCast(rcv.indicesStrides.items.len);
            _ = try SparseTensorIndexCOO.StartIndicesStridesVector(__builder, indicesStrides_len);
            {
                var j = indicesStrides_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prepend(i64, rcv.indicesStrides.items[@as(u32, @bitCast(j))]);
                }
                indicesStrides_off = try __builder.endVector(@bitCast(indicesStrides_len));
            }
        }

        try SparseTensorIndexCOO.Start(__builder);
        try SparseTensorIndexCOO.AddIndicesType(__builder, indicesType_off);
        try SparseTensorIndexCOO.AddIndicesStrides(__builder, indicesStrides_off);
        const indicesBuffer_off = if (rcv.indicesBuffer) |x| try x.Pack(__builder, __pack_opts) else 0;
        try SparseTensorIndexCOO.AddIndicesBuffer(__builder, indicesBuffer_off);
        try SparseTensorIndexCOO.AddIsCanonical(__builder, rcv.isCanonical);
        return SparseTensorIndexCOO.End(__builder);
    }

    pub fn UnpackTo(rcv: SparseTensorIndexCOO, t: *SparseTensorIndexCOOT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        if (rcv.IndicesType()) |x| {
            if (t.indicesType == null) {
                t.indicesType = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                t.indicesType.?.* = .{};
            }
            try org.apache.arrow.flatbuf.IntT.UnpackTo(x, t.indicesType.?, __pack_opts);
        }

        const indicesStrides_len = rcv.IndicesStridesLen();
        t.indicesStrides = try std.ArrayList(i64).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(indicesStrides_len)));
        t.indicesStrides.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < indicesStrides_len) : (j += 1) {
                t.indicesStrides.items[j] = rcv.IndicesStrides(j).?;
            }
        }

        if (rcv.IndicesBuffer()) |x| {
            if (t.indicesBuffer == null) {
                t.indicesBuffer = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BufferT);
                t.indicesBuffer.?.* = .{};
            }
            try org.apache.arrow.flatbuf.BufferT.UnpackTo(x, t.indicesBuffer.?, __pack_opts);
        }

        t.isCanonical = rcv.IsCanonical();
    }

    pub fn Unpack(rcv: SparseTensorIndexCOO, __pack_opts: fb.common.PackOptions) fb.common.PackError!SparseTensorIndexCOOT {
        var t = SparseTensorIndexCOOT{};
        try SparseTensorIndexCOOT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *SparseTensorIndexCOOT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        if (self.indicesType) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        self.indicesStrides.deinit(allocator);
        if (self.indicesBuffer) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
    }
};

pub const SparseTensorIndexCOO = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.SparseTensorIndexCOO {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.SparseTensorIndexCOO.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.SparseTensorIndexCOO {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.SparseTensorIndexCOO.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) SparseTensorIndexCOO {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: SparseTensorIndexCOO) fb.Table {
        return x._tab;
    }

    /// The type of values in indicesBuffer
    pub fn IndicesType(rcv: SparseTensorIndexCOO) ?org.apache.arrow.flatbuf.Int {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.Int.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// Non-negative byte offsets to advance one value cell along each dimension
    /// If omitted, default to row-major order (C-like).
    pub fn IndicesStrides(rcv: SparseTensorIndexCOO, j: usize) ?i64 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.read(i64, a + @as(u32, @intCast(j)) * 8);
        }
        return 0;
    }

    pub fn IndicesStridesLen(rcv: SparseTensorIndexCOO) u32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn MutateIndicesStrides(rcv: SparseTensorIndexCOO, j: usize, n: i64) bool {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.mutate(i64, a + @as(u32, @intCast(j)) * 8, n);
        }
        return false;
    }

    /// The location and size of the indices matrix's data
    pub fn IndicesBuffer(rcv: SparseTensorIndexCOO) ?org.apache.arrow.flatbuf.Buffer {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            const x = o + rcv._tab.pos;
            return org.apache.arrow.flatbuf.Buffer.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// This flag is true if and only if the indices matrix is sorted in
    /// row-major order, and does not have duplicated entries.
    /// This sort order is the same as of Tensorflow's SparseTensor,
    /// but it is inverse order of SciPy's canonical coo_matrix
    /// (SciPy employs column-major order for its coo_matrix).
    pub fn IsCanonical(rcv: SparseTensorIndexCOO) bool {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.read(bool, o + rcv._tab.pos);
        }
        return false;
    }

    pub fn MutateIsCanonical(rcv: SparseTensorIndexCOO, n: bool) bool {
        return rcv._tab.mutateSlot(bool, 10, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(4);
    }
    pub fn AddIndicesType(__builder: *Builder, indicesType: u32) !void {
        try __builder.prependSlotUOff(0, indicesType, 0);
    }

    pub fn AddIndicesStrides(__builder: *Builder, indicesStrides: u32) !void {
        try __builder.prependSlotUOff(1, indicesStrides, 0);
    }

    pub fn StartIndicesStridesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(8, num_elems, 8);
    }
    pub fn AddIndicesBuffer(__builder: *Builder, indicesBuffer: u32) !void {
        try __builder.prependSlotStruct(2, indicesBuffer, 0);
    }

    pub fn AddIsCanonical(__builder: *Builder, isCanonical: bool) !void {
        try __builder.prependSlot(bool, 3, isCanonical, false);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: SparseTensorIndexCOO, __pack_opts: fb.common.PackOptions) !SparseTensorIndexCOOT {
        return SparseTensorIndexCOOT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = SparseTensorIndexCOOT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = SparseTensorIndexCOO.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
