//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.fbs
//! file ident: //SparseTensor.fbs
//! typename    org.apache.arrow.flatbuf.SparseMatrixIndexCSX
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Int = @import("Int.fb.zig").Int;
                const IntT = @import("Int.fb.zig").IntT;
                const SparseMatrixIndexCSX = @import("SparseMatrixIndexCSX.fb.zig").SparseMatrixIndexCSX;
                const SparseMatrixIndexCSXT = @import("SparseMatrixIndexCSX.fb.zig").SparseMatrixIndexCSXT;
                const Buffer = @import("Buffer.fb.zig").Buffer;
                const BufferT = @import("Buffer.fb.zig").BufferT;
                const SparseMatrixCompressedAxis = @import("SparseMatrixCompressedAxis.fb.zig").SparseMatrixCompressedAxis;
            };
        };
    };
};

/// Compressed Sparse format, that is matrix-specific.
pub const SparseMatrixIndexCSXT = struct {
    /// Which axis, row or column, is compressed
    compressedAxis: org.apache.arrow.flatbuf.SparseMatrixCompressedAxis = @as(org.apache.arrow.flatbuf.SparseMatrixCompressedAxis, @enumFromInt(0)),
    /// The type of values in indptrBuffer
    indptrType: ?*org.apache.arrow.flatbuf.IntT = null,
    /// indptrBuffer stores the location and size of indptr array that
    /// represents the range of the rows.
    /// The i-th row spans from `indptr[i]` to `indptr[i+1]` in the data.
    /// The length of this array is 1 + (the number of rows), and the type
    /// of index value is long.
    ///
    /// For example, let X be the following 6x4 matrix:
    /// ```text
    ///   X := [[0, 1, 2, 0],
    ///         [0, 0, 3, 0],
    ///         [0, 4, 0, 5],
    ///         [0, 0, 0, 0],
    ///         [6, 0, 7, 8],
    ///         [0, 9, 0, 0]].
    /// ```
    /// The array of non-zero values in X is:
    /// ```text
    ///   values(X) = [1, 2, 3, 4, 5, 6, 7, 8, 9].
    /// ```
    /// And the indptr of X is:
    /// ```text
    ///   indptr(X) = [0, 2, 3, 5, 5, 8, 10].
    /// ```
    indptrBuffer: ?*org.apache.arrow.flatbuf.BufferT = null,
    /// The type of values in indicesBuffer
    indicesType: ?*org.apache.arrow.flatbuf.IntT = null,
    /// indicesBuffer stores the location and size of the array that
    /// contains the column indices of the corresponding non-zero values.
    /// The type of index value is long.
    ///
    /// For example, the indices of the above X are:
    /// ```text
    ///   indices(X) = [1, 2, 2, 1, 3, 0, 2, 3, 1].
    /// ```
    /// Note that the indices are sorted in lexicographical order for each row.
    indicesBuffer: ?*org.apache.arrow.flatbuf.BufferT = null,

    pub fn Pack(rcv: SparseMatrixIndexCSXT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const indptrType_off = if (rcv.indptrType) |x| try x.Pack(__builder, __pack_opts) else 0;

        const indicesType_off = if (rcv.indicesType) |x| try x.Pack(__builder, __pack_opts) else 0;

        try SparseMatrixIndexCSX.Start(__builder);
        try SparseMatrixIndexCSX.AddCompressedAxis(__builder, rcv.compressedAxis);
        try SparseMatrixIndexCSX.AddIndptrType(__builder, indptrType_off);
        const indptrBuffer_off = if (rcv.indptrBuffer) |x| try x.Pack(__builder, __pack_opts) else 0;
        try SparseMatrixIndexCSX.AddIndptrBuffer(__builder, indptrBuffer_off);
        try SparseMatrixIndexCSX.AddIndicesType(__builder, indicesType_off);
        const indicesBuffer_off = if (rcv.indicesBuffer) |x| try x.Pack(__builder, __pack_opts) else 0;
        try SparseMatrixIndexCSX.AddIndicesBuffer(__builder, indicesBuffer_off);
        return SparseMatrixIndexCSX.End(__builder);
    }

    pub fn UnpackTo(rcv: SparseMatrixIndexCSX, t: *SparseMatrixIndexCSXT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.compressedAxis = rcv.CompressedAxis();

        if (rcv.IndptrType()) |x| {
            if (t.indptrType == null) {
                t.indptrType = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                t.indptrType.?.* = .{};
            }
            try org.apache.arrow.flatbuf.IntT.UnpackTo(x, t.indptrType.?, __pack_opts);
        }

        if (rcv.IndptrBuffer()) |x| {
            if (t.indptrBuffer == null) {
                t.indptrBuffer = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BufferT);
                t.indptrBuffer.?.* = .{};
            }
            try org.apache.arrow.flatbuf.BufferT.UnpackTo(x, t.indptrBuffer.?, __pack_opts);
        }

        if (rcv.IndicesType()) |x| {
            if (t.indicesType == null) {
                t.indicesType = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                t.indicesType.?.* = .{};
            }
            try org.apache.arrow.flatbuf.IntT.UnpackTo(x, t.indicesType.?, __pack_opts);
        }

        if (rcv.IndicesBuffer()) |x| {
            if (t.indicesBuffer == null) {
                t.indicesBuffer = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BufferT);
                t.indicesBuffer.?.* = .{};
            }
            try org.apache.arrow.flatbuf.BufferT.UnpackTo(x, t.indicesBuffer.?, __pack_opts);
        }
    }

    pub fn Unpack(rcv: SparseMatrixIndexCSX, __pack_opts: fb.common.PackOptions) fb.common.PackError!SparseMatrixIndexCSXT {
        var t = SparseMatrixIndexCSXT{};
        try SparseMatrixIndexCSXT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *SparseMatrixIndexCSXT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        if (self.indptrType) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        if (self.indptrBuffer) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        if (self.indicesType) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        if (self.indicesBuffer) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
    }
};

pub const SparseMatrixIndexCSX = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.SparseMatrixIndexCSX {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.SparseMatrixIndexCSX.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.SparseMatrixIndexCSX {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.SparseMatrixIndexCSX.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) SparseMatrixIndexCSX {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: SparseMatrixIndexCSX) fb.Table {
        return x._tab;
    }

    /// Which axis, row or column, is compressed
    pub fn CompressedAxis(rcv: SparseMatrixIndexCSX) org.apache.arrow.flatbuf.SparseMatrixCompressedAxis {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.SparseMatrixCompressedAxis, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.SparseMatrixCompressedAxis, @enumFromInt(0));
    }

    pub fn MutateCompressedAxis(rcv: SparseMatrixIndexCSX, n: org.apache.arrow.flatbuf.SparseMatrixCompressedAxis) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.SparseMatrixCompressedAxis, 4, n);
    }

    /// The type of values in indptrBuffer
    pub fn IndptrType(rcv: SparseMatrixIndexCSX) ?org.apache.arrow.flatbuf.Int {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.Int.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// indptrBuffer stores the location and size of indptr array that
    /// represents the range of the rows.
    /// The i-th row spans from `indptr[i]` to `indptr[i+1]` in the data.
    /// The length of this array is 1 + (the number of rows), and the type
    /// of index value is long.
    ///
    /// For example, let X be the following 6x4 matrix:
    /// ```text
    ///   X := [[0, 1, 2, 0],
    ///         [0, 0, 3, 0],
    ///         [0, 4, 0, 5],
    ///         [0, 0, 0, 0],
    ///         [6, 0, 7, 8],
    ///         [0, 9, 0, 0]].
    /// ```
    /// The array of non-zero values in X is:
    /// ```text
    ///   values(X) = [1, 2, 3, 4, 5, 6, 7, 8, 9].
    /// ```
    /// And the indptr of X is:
    /// ```text
    ///   indptr(X) = [0, 2, 3, 5, 5, 8, 10].
    /// ```
    pub fn IndptrBuffer(rcv: SparseMatrixIndexCSX) ?org.apache.arrow.flatbuf.Buffer {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            const x = o + rcv._tab.pos;
            return org.apache.arrow.flatbuf.Buffer.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// The type of values in indicesBuffer
    pub fn IndicesType(rcv: SparseMatrixIndexCSX) ?org.apache.arrow.flatbuf.Int {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.Int.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// indicesBuffer stores the location and size of the array that
    /// contains the column indices of the corresponding non-zero values.
    /// The type of index value is long.
    ///
    /// For example, the indices of the above X are:
    /// ```text
    ///   indices(X) = [1, 2, 2, 1, 3, 0, 2, 3, 1].
    /// ```
    /// Note that the indices are sorted in lexicographical order for each row.
    pub fn IndicesBuffer(rcv: SparseMatrixIndexCSX) ?org.apache.arrow.flatbuf.Buffer {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const x = o + rcv._tab.pos;
            return org.apache.arrow.flatbuf.Buffer.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(5);
    }
    pub fn AddCompressedAxis(__builder: *Builder, compressedAxis: org.apache.arrow.flatbuf.SparseMatrixCompressedAxis) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.SparseMatrixCompressedAxis, 0, compressedAxis, @as(org.apache.arrow.flatbuf.SparseMatrixCompressedAxis, @enumFromInt(0)));
    }

    pub fn AddIndptrType(__builder: *Builder, indptrType: u32) !void {
        try __builder.prependSlotUOff(1, indptrType, 0);
    }

    pub fn AddIndptrBuffer(__builder: *Builder, indptrBuffer: u32) !void {
        try __builder.prependSlotStruct(2, indptrBuffer, 0);
    }

    pub fn AddIndicesType(__builder: *Builder, indicesType: u32) !void {
        try __builder.prependSlotUOff(3, indicesType, 0);
    }

    pub fn AddIndicesBuffer(__builder: *Builder, indicesBuffer: u32) !void {
        try __builder.prependSlotStruct(4, indicesBuffer, 0);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: SparseMatrixIndexCSX, __pack_opts: fb.common.PackOptions) !SparseMatrixIndexCSXT {
        return SparseMatrixIndexCSXT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = SparseMatrixIndexCSXT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = SparseMatrixIndexCSX.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
