//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.fbs
//! file ident: //SparseTensor.fbs
//! typename    org.apache.arrow.flatbuf.SparseTensorIndex
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const SparseTensorIndexCOO = @import("SparseTensorIndexCOO.fb.zig").SparseTensorIndexCOO;
                const SparseTensorIndexCOOT = @import("SparseTensorIndexCOO.fb.zig").SparseTensorIndexCOOT;
                const SparseTensorIndexCSF = @import("SparseTensorIndexCSF.fb.zig").SparseTensorIndexCSF;
                const SparseTensorIndexCSFT = @import("SparseTensorIndexCSF.fb.zig").SparseTensorIndexCSFT;
                const SparseMatrixIndexCSX = @import("SparseMatrixIndexCSX.fb.zig").SparseMatrixIndexCSX;
                const SparseMatrixIndexCSXT = @import("SparseMatrixIndexCSX.fb.zig").SparseMatrixIndexCSXT;
                const SparseTensorIndex = @import("SparseTensorIndex.fb.zig").SparseTensorIndex;
            };
        };
    };
};

pub const SparseTensorIndex = union(enum) {
    NONE,
    SparseTensorIndexCOO: org.apache.arrow.flatbuf.SparseTensorIndexCOO,
    SparseMatrixIndexCSX: org.apache.arrow.flatbuf.SparseMatrixIndexCSX,
    SparseTensorIndexCSF: org.apache.arrow.flatbuf.SparseTensorIndexCSF,

    pub const Tag = std.meta.Tag(@This());
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};

pub const SparseTensorIndexT = union(SparseTensorIndex.Tag) {
    NONE: void,
    SparseTensorIndexCOO: ?*org.apache.arrow.flatbuf.SparseTensorIndexCOOT,
    SparseMatrixIndexCSX: ?*org.apache.arrow.flatbuf.SparseMatrixIndexCSXT,
    SparseTensorIndexCSF: ?*org.apache.arrow.flatbuf.SparseTensorIndexCSFT,

    pub fn deinit(self: *SparseTensorIndexT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        switch (self.*) {
            .NONE => {},
            .SparseTensorIndexCOO => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.SparseTensorIndexCOO = null;
            },
            .SparseMatrixIndexCSX => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.SparseMatrixIndexCSX = null;
            },
            .SparseTensorIndexCSF => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.SparseTensorIndexCSF = null;
            },
        }
    }

    pub fn Pack(rcv: SparseTensorIndexT, __builder: *Builder, __pack_opts: fb.common.PackOptions) !u32 {
        _ = .{ __builder, __pack_opts };
        // std.debug.print("pack() SparseTensorIndexT rcv=.{s}\n", .{@tagName(rcv)});
        switch (rcv) {
            .NONE => {},
            .SparseTensorIndexCOO => |x| return x.?.Pack(__builder, __pack_opts),
            .SparseMatrixIndexCSX => |x| return x.?.Pack(__builder, __pack_opts),
            .SparseTensorIndexCSF => |x| return x.?.Pack(__builder, __pack_opts),
        }
        return 0;
    }

    pub fn Unpack(rcv: SparseTensorIndex.Tag, table: fb.Table, __pack_opts: fb.common.PackOptions) !SparseTensorIndexT {
        _ = .{ table, __pack_opts };
        // std.debug.print("unpack() SparseTensorIndex rcv=.{s}\n", .{@tagName(rcv)});
        switch (rcv) {
            .NONE => return .NONE,
            .SparseTensorIndexCOO => {
                const x = org.apache.arrow.flatbuf.SparseTensorIndexCOO.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.SparseTensorIndexCOOT);
                ptr.* = try org.apache.arrow.flatbuf.SparseTensorIndexCOOT.Unpack(x, __pack_opts);
                return .{ .SparseTensorIndexCOO = ptr };
            },
            .SparseMatrixIndexCSX => {
                const x = org.apache.arrow.flatbuf.SparseMatrixIndexCSX.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.SparseMatrixIndexCSXT);
                ptr.* = try org.apache.arrow.flatbuf.SparseMatrixIndexCSXT.Unpack(x, __pack_opts);
                return .{ .SparseMatrixIndexCSX = ptr };
            },
            .SparseTensorIndexCSF => {
                const x = org.apache.arrow.flatbuf.SparseTensorIndexCSF.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.SparseTensorIndexCSFT);
                ptr.* = try org.apache.arrow.flatbuf.SparseTensorIndexCSFT.Unpack(x, __pack_opts);
                return .{ .SparseTensorIndexCSF = ptr };
            },
        }
        unreachable;
    }
};

test {
    var obj: SparseTensorIndexT = .NONE;
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    const table = fb.Table.init(bytes, 0);
    const obj2 = try SparseTensorIndexT.Unpack(.NONE, table, opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
