//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/SparseTensor.fbs
//! file ident: //SparseTensor.fbs
//! typename    org.apache.arrow.flatbuf.SparseTensorIndexCSF
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const Int = @import("Int.fb.zig").Int;
                const IntT = @import("Int.fb.zig").IntT;
                const SparseTensorIndexCSF = @import("SparseTensorIndexCSF.fb.zig").SparseTensorIndexCSF;
                const SparseTensorIndexCSFT = @import("SparseTensorIndexCSF.fb.zig").SparseTensorIndexCSFT;
                const Buffer = @import("Buffer.fb.zig").Buffer;
                const BufferT = @import("Buffer.fb.zig").BufferT;
            };
        };
    };
};

/// Compressed Sparse Fiber (CSF) sparse tensor index.
pub const SparseTensorIndexCSFT = struct {
    /// CSF is a generalization of compressed sparse row (CSR) index.
    /// See [smith2017knl](http://shaden.io/pub-files/smith2017knl.pdf)
    ///
    /// CSF index recursively compresses each dimension of a tensor into a set
    /// of prefix trees. Each path from a root to leaf forms one tensor
    /// non-zero index. CSF is implemented with two arrays of buffers and one
    /// array of integers.
    ///
    /// For example, let X be a 2x3x4x5 tensor and let it have the following
    /// 8 non-zero values:
    /// ```text
    ///   X[0, 0, 0, 1] := 1
    ///   X[0, 0, 0, 2] := 2
    ///   X[0, 1, 0, 0] := 3
    ///   X[0, 1, 0, 2] := 4
    ///   X[0, 1, 1, 0] := 5
    ///   X[1, 1, 1, 0] := 6
    ///   X[1, 1, 1, 1] := 7
    ///   X[1, 1, 1, 2] := 8
    /// ```
    /// As a prefix tree this would be represented as:
    /// ```text
    ///         0          1
    ///        / \         |
    ///       0   1        1
    ///      /   / \       |
    ///     0   0   1      1
    ///    /|  /|   |    /| |
    ///   1 2 0 2   0   0 1 2
    /// ```
    /// The type of values in indptrBuffers
    indptrType: ?*org.apache.arrow.flatbuf.IntT = null,
    /// indptrBuffers stores the sparsity structure.
    /// Each two consecutive dimensions in a tensor correspond to a buffer in
    /// indptrBuffers. A pair of consecutive values at `indptrBuffers[dim][i]`
    /// and `indptrBuffers[dim][i + 1]` signify a range of nodes in
    /// `indicesBuffers[dim + 1]` who are children of `indicesBuffers[dim][i]` node.
    ///
    /// For example, the indptrBuffers for the above X are:
    /// ```text
    ///   indptrBuffer(X) = [
    ///                       [0, 2, 3],
    ///                       [0, 1, 3, 4],
    ///                       [0, 2, 4, 5, 8]
    ///                     ].
    /// ```
    indptrBuffers: std.ArrayList(org.apache.arrow.flatbuf.BufferT) = .{},
    /// The type of values in indicesBuffers
    indicesType: ?*org.apache.arrow.flatbuf.IntT = null,
    /// indicesBuffers stores values of nodes.
    /// Each tensor dimension corresponds to a buffer in indicesBuffers.
    /// For example, the indicesBuffers for the above X are:
    /// ```text
    ///   indicesBuffer(X) = [
    ///                        [0, 1],
    ///                        [0, 1, 1],
    ///                        [0, 0, 1, 1],
    ///                        [1, 2, 0, 2, 0, 0, 1, 2]
    ///                      ].
    /// ```
    indicesBuffers: std.ArrayList(org.apache.arrow.flatbuf.BufferT) = .{},
    /// axisOrder stores the sequence in which dimensions were traversed to
    /// produce the prefix tree.
    /// For example, the axisOrder for the above X is:
    /// ```text
    ///   axisOrder(X) = [0, 1, 2, 3].
    /// ```
    axisOrder: std.ArrayList(i32) = .{},

    pub fn Pack(rcv: SparseTensorIndexCSFT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const indptrType_off = if (rcv.indptrType) |x| try x.Pack(__builder, __pack_opts) else 0;

        var indptrBuffers_off: u32 = 0;
        if (rcv.indptrBuffers.items.len != 0) {
            const indptrBuffers_len: i32 = @intCast(rcv.indptrBuffers.items.len);
            _ = try SparseTensorIndexCSF.StartIndptrBuffersVector(__builder, indptrBuffers_len);
            {
                var j = indptrBuffers_len - 1;
                while (j >= 0) : (j -= 1) {
                    _ = try rcv.indptrBuffers.items[@as(u32, @bitCast(j))].Pack(__builder, __pack_opts);
                }
                indptrBuffers_off = try __builder.endVector(@bitCast(indptrBuffers_len));
            }
        }

        const indicesType_off = if (rcv.indicesType) |x| try x.Pack(__builder, __pack_opts) else 0;

        var indicesBuffers_off: u32 = 0;
        if (rcv.indicesBuffers.items.len != 0) {
            const indicesBuffers_len: i32 = @intCast(rcv.indicesBuffers.items.len);
            _ = try SparseTensorIndexCSF.StartIndicesBuffersVector(__builder, indicesBuffers_len);
            {
                var j = indicesBuffers_len - 1;
                while (j >= 0) : (j -= 1) {
                    _ = try rcv.indicesBuffers.items[@as(u32, @bitCast(j))].Pack(__builder, __pack_opts);
                }
                indicesBuffers_off = try __builder.endVector(@bitCast(indicesBuffers_len));
            }
        }

        var axisOrder_off: u32 = 0;
        if (rcv.axisOrder.items.len != 0) {
            const axisOrder_len: i32 = @intCast(rcv.axisOrder.items.len);
            _ = try SparseTensorIndexCSF.StartAxisOrderVector(__builder, axisOrder_len);
            {
                var j = axisOrder_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prepend(i32, rcv.axisOrder.items[@as(u32, @bitCast(j))]);
                }
                axisOrder_off = try __builder.endVector(@bitCast(axisOrder_len));
            }
        }

        try SparseTensorIndexCSF.Start(__builder);
        try SparseTensorIndexCSF.AddIndptrType(__builder, indptrType_off);
        try SparseTensorIndexCSF.AddIndptrBuffers(__builder, indptrBuffers_off);
        try SparseTensorIndexCSF.AddIndicesType(__builder, indicesType_off);
        try SparseTensorIndexCSF.AddIndicesBuffers(__builder, indicesBuffers_off);
        try SparseTensorIndexCSF.AddAxisOrder(__builder, axisOrder_off);
        return SparseTensorIndexCSF.End(__builder);
    }

    pub fn UnpackTo(rcv: SparseTensorIndexCSF, t: *SparseTensorIndexCSFT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        if (rcv.IndptrType()) |x| {
            if (t.indptrType == null) {
                t.indptrType = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                t.indptrType.?.* = .{};
            }
            try org.apache.arrow.flatbuf.IntT.UnpackTo(x, t.indptrType.?, __pack_opts);
        }

        const indptrBuffers_len = rcv.IndptrBuffersLen();
        t.indptrBuffers = try std.ArrayList(org.apache.arrow.flatbuf.BufferT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(indptrBuffers_len)));
        t.indptrBuffers.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < indptrBuffers_len) : (j += 1) {
                const x = rcv.IndptrBuffers(j).?;
                t.indptrBuffers.items[j] = try x.Unpack(__pack_opts);
            }
        }

        if (rcv.IndicesType()) |x| {
            if (t.indicesType == null) {
                t.indicesType = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                t.indicesType.?.* = .{};
            }
            try org.apache.arrow.flatbuf.IntT.UnpackTo(x, t.indicesType.?, __pack_opts);
        }

        const indicesBuffers_len = rcv.IndicesBuffersLen();
        t.indicesBuffers = try std.ArrayList(org.apache.arrow.flatbuf.BufferT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(indicesBuffers_len)));
        t.indicesBuffers.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < indicesBuffers_len) : (j += 1) {
                const x = rcv.IndicesBuffers(j).?;
                t.indicesBuffers.items[j] = try x.Unpack(__pack_opts);
            }
        }

        const axisOrder_len = rcv.AxisOrderLen();
        t.axisOrder = try std.ArrayList(i32).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(axisOrder_len)));
        t.axisOrder.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < axisOrder_len) : (j += 1) {
                t.axisOrder.items[j] = rcv.AxisOrder(j).?;
            }
        }
    }

    pub fn Unpack(rcv: SparseTensorIndexCSF, __pack_opts: fb.common.PackOptions) fb.common.PackError!SparseTensorIndexCSFT {
        var t = SparseTensorIndexCSFT{};
        try SparseTensorIndexCSFT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *SparseTensorIndexCSFT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        if (self.indptrType) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        for (self.indptrBuffers.items) |*it| it.deinit(allocator);
        self.indptrBuffers.deinit(allocator);
        if (self.indicesType) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
        for (self.indicesBuffers.items) |*it| it.deinit(allocator);
        self.indicesBuffers.deinit(allocator);
        self.axisOrder.deinit(allocator);
    }
};

pub const SparseTensorIndexCSF = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.SparseTensorIndexCSF {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.SparseTensorIndexCSF.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.SparseTensorIndexCSF {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.SparseTensorIndexCSF.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) SparseTensorIndexCSF {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: SparseTensorIndexCSF) fb.Table {
        return x._tab;
    }

    /// CSF is a generalization of compressed sparse row (CSR) index.
    /// See [smith2017knl](http://shaden.io/pub-files/smith2017knl.pdf)
    ///
    /// CSF index recursively compresses each dimension of a tensor into a set
    /// of prefix trees. Each path from a root to leaf forms one tensor
    /// non-zero index. CSF is implemented with two arrays of buffers and one
    /// array of integers.
    ///
    /// For example, let X be a 2x3x4x5 tensor and let it have the following
    /// 8 non-zero values:
    /// ```text
    ///   X[0, 0, 0, 1] := 1
    ///   X[0, 0, 0, 2] := 2
    ///   X[0, 1, 0, 0] := 3
    ///   X[0, 1, 0, 2] := 4
    ///   X[0, 1, 1, 0] := 5
    ///   X[1, 1, 1, 0] := 6
    ///   X[1, 1, 1, 1] := 7
    ///   X[1, 1, 1, 2] := 8
    /// ```
    /// As a prefix tree this would be represented as:
    /// ```text
    ///         0          1
    ///        / \         |
    ///       0   1        1
    ///      /   / \       |
    ///     0   0   1      1
    ///    /|  /|   |    /| |
    ///   1 2 0 2   0   0 1 2
    /// ```
    /// The type of values in indptrBuffers
    pub fn IndptrType(rcv: SparseTensorIndexCSF) ?org.apache.arrow.flatbuf.Int {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.Int.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// indptrBuffers stores the sparsity structure.
    /// Each two consecutive dimensions in a tensor correspond to a buffer in
    /// indptrBuffers. A pair of consecutive values at `indptrBuffers[dim][i]`
    /// and `indptrBuffers[dim][i + 1]` signify a range of nodes in
    /// `indicesBuffers[dim + 1]` who are children of `indicesBuffers[dim][i]` node.
    ///
    /// For example, the indptrBuffers for the above X are:
    /// ```text
    ///   indptrBuffer(X) = [
    ///                       [0, 2, 3],
    ///                       [0, 1, 3, 4],
    ///                       [0, 2, 4, 5, 8]
    ///                     ].
    /// ```
    pub fn IndptrBuffers(rcv: SparseTensorIndexCSF, j: usize) ?org.apache.arrow.flatbuf.Buffer {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 16;
            return org.apache.arrow.flatbuf.Buffer.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn IndptrBuffersLen(rcv: SparseTensorIndexCSF) u32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// The type of values in indicesBuffers
    pub fn IndicesType(rcv: SparseTensorIndexCSF) ?org.apache.arrow.flatbuf.Int {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            const x = rcv._tab.indirect(o + rcv._tab.pos);
            return org.apache.arrow.flatbuf.Int.init(rcv._tab.bytes, x);
        }
        return null;
    }

    /// indicesBuffers stores values of nodes.
    /// Each tensor dimension corresponds to a buffer in indicesBuffers.
    /// For example, the indicesBuffers for the above X are:
    /// ```text
    ///   indicesBuffer(X) = [
    ///                        [0, 1],
    ///                        [0, 1, 1],
    ///                        [0, 0, 1, 1],
    ///                        [1, 2, 0, 2, 0, 0, 1, 2]
    ///                      ].
    /// ```
    pub fn IndicesBuffers(rcv: SparseTensorIndexCSF, j: usize) ?org.apache.arrow.flatbuf.Buffer {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 16;
            return org.apache.arrow.flatbuf.Buffer.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn IndicesBuffersLen(rcv: SparseTensorIndexCSF) u32 {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// axisOrder stores the sequence in which dimensions were traversed to
    /// produce the prefix tree.
    /// For example, the axisOrder for the above X is:
    /// ```text
    ///   axisOrder(X) = [0, 1, 2, 3].
    /// ```
    pub fn AxisOrder(rcv: SparseTensorIndexCSF, j: usize) ?i32 {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.read(i32, a + @as(u32, @intCast(j)) * 4);
        }
        return 0;
    }

    pub fn AxisOrderLen(rcv: SparseTensorIndexCSF) u32 {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn MutateAxisOrder(rcv: SparseTensorIndexCSF, j: usize, n: i32) bool {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.mutate(i32, a + @as(u32, @intCast(j)) * 4, n);
        }
        return false;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(5);
    }
    pub fn AddIndptrType(__builder: *Builder, indptrType: u32) !void {
        try __builder.prependSlotUOff(0, indptrType, 0);
    }

    pub fn AddIndptrBuffers(__builder: *Builder, indptrBuffers: u32) !void {
        try __builder.prependSlotUOff(1, indptrBuffers, 0);
    }

    pub fn StartIndptrBuffersVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(16, num_elems, 8);
    }
    pub fn AddIndicesType(__builder: *Builder, indicesType: u32) !void {
        try __builder.prependSlotUOff(2, indicesType, 0);
    }

    pub fn AddIndicesBuffers(__builder: *Builder, indicesBuffers: u32) !void {
        try __builder.prependSlotUOff(3, indicesBuffers, 0);
    }

    pub fn StartIndicesBuffersVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(16, num_elems, 8);
    }
    pub fn AddAxisOrder(__builder: *Builder, axisOrder: u32) !void {
        try __builder.prependSlotUOff(4, axisOrder, 0);
    }

    pub fn StartAxisOrderVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 4);
    }
    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: SparseTensorIndexCSF, __pack_opts: fb.common.PackOptions) !SparseTensorIndexCSFT {
        return SparseTensorIndexCSFT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = SparseTensorIndexCSFT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = SparseTensorIndexCSF.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
