//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Tensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Tensor.fbs
//! file ident: //Tensor.fbs
//! typename    org.apache.arrow.flatbuf.Tensor
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const TensorDim = @import("TensorDim.fb.zig").TensorDim;
                const TensorDimT = @import("TensorDim.fb.zig").TensorDimT;
                const Type = @import("Type.fb.zig").Type;
                const TypeT = @import("Type.fb.zig").TypeT;
                const Buffer = @import("Buffer.fb.zig").Buffer;
                const BufferT = @import("Buffer.fb.zig").BufferT;
                const Tensor = @import("Tensor.fb.zig").Tensor;
                const TensorT = @import("Tensor.fb.zig").TensorT;
            };
        };
    };
};

pub const __file_ident: fb.Builder.Fid = "".*;
pub const __file_ext = "";

pub const TensorT = struct {
    /// The type of data contained in a value cell. Currently only fixed-width
    /// value types are supported, no strings or nested types
    type: org.apache.arrow.flatbuf.TypeT = @as(org.apache.arrow.flatbuf.Type.Tag, @enumFromInt(0)),
    /// The dimensions of the tensor, optionally named
    shape: std.ArrayList(org.apache.arrow.flatbuf.TensorDimT) = .{},
    /// Non-negative byte offsets to advance one value cell along each dimension
    /// If omitted, default to row-major order (C-like).
    strides: std.ArrayList(i64) = .{},
    /// The location and size of the tensor's data
    data: ?*org.apache.arrow.flatbuf.BufferT = null,

    pub fn Pack(rcv: TensorT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const type_off = try rcv.type.Pack(__builder, __pack_opts);

        var shape_off: u32 = 0;
        if (rcv.shape.items.len != 0) {
            const shape_len: i32 = @intCast(rcv.shape.items.len);
            try __tmp_offsets.ensureTotalCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(shape_len)));
            __tmp_offsets.items.len = @as(u32, @bitCast(shape_len));
            for (__tmp_offsets.items, 0..) |*off, j| {
                off.* = try org.apache.arrow.flatbuf.TensorDimT.Pack(rcv.shape.items[j], __builder, __pack_opts);
            }
            _ = try Tensor.StartShapeVector(__builder, shape_len);
            {
                var j = shape_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prependUOff(__tmp_offsets.items[@as(u32, @bitCast(j))]);
                }
                shape_off = try __builder.endVector(@bitCast(shape_len));
            }
        }

        var strides_off: u32 = 0;
        if (rcv.strides.items.len != 0) {
            const strides_len: i32 = @intCast(rcv.strides.items.len);
            _ = try Tensor.StartStridesVector(__builder, strides_len);
            {
                var j = strides_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prepend(i64, rcv.strides.items[@as(u32, @bitCast(j))]);
                }
                strides_off = try __builder.endVector(@bitCast(strides_len));
            }
        }

        try Tensor.Start(__builder);
        try Tensor.AddTypeType(__builder, rcv.type);
        try Tensor.AddType(__builder, type_off);
        try Tensor.AddShape(__builder, shape_off);
        try Tensor.AddStrides(__builder, strides_off);
        const data_off = if (rcv.data) |x| try x.Pack(__builder, __pack_opts) else 0;
        try Tensor.AddData(__builder, data_off);
        return Tensor.End(__builder);
    }

    pub fn UnpackTo(rcv: Tensor, t: *TensorT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        if (rcv.Type()) |_tab| {
            t.type = try org.apache.arrow.flatbuf.TypeT.Unpack(rcv.TypeType(), _tab, __pack_opts);
        }

        const shape_len = rcv.ShapeLen();
        t.shape = try std.ArrayList(org.apache.arrow.flatbuf.TensorDimT).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(shape_len)));
        t.shape.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < shape_len) : (j += 1) {
                const x = rcv.Shape(j).?;
                t.shape.items[j] = try x.Unpack(__pack_opts);
            }
        }

        const strides_len = rcv.StridesLen();
        t.strides = try std.ArrayList(i64).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(strides_len)));
        t.strides.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < strides_len) : (j += 1) {
                t.strides.items[j] = rcv.Strides(j).?;
            }
        }

        if (rcv.Data()) |x| {
            if (t.data == null) {
                t.data = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BufferT);
                t.data.?.* = .{};
            }
            try org.apache.arrow.flatbuf.BufferT.UnpackTo(x, t.data.?, __pack_opts);
        }
    }

    pub fn Unpack(rcv: Tensor, __pack_opts: fb.common.PackOptions) fb.common.PackError!TensorT {
        var t = TensorT{};
        try TensorT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *TensorT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        self.type.deinit(allocator);
        for (self.shape.items) |*it| it.deinit(allocator);
        self.shape.deinit(allocator);
        self.strides.deinit(allocator);
        if (self.data) |x| {
            x.deinit(allocator);
            allocator.destroy(x);
        }
    }
};

pub const Tensor = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Tensor {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Tensor.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Tensor {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Tensor.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Tensor {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Tensor) fb.Table {
        return x._tab;
    }

    pub fn TypeType(rcv: Tensor) org.apache.arrow.flatbuf.Type.Tag {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.Type.Tag, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.Type.Tag, @enumFromInt(0));
    }

    pub fn MutateTypeType(rcv: Tensor, n: org.apache.arrow.flatbuf.Type) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.Type, 4, n);
    }

    /// The type of data contained in a value cell. Currently only fixed-width
    /// value types are supported, no strings or nested types
    pub fn Type(rcv: Tensor) ?fb.Table {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.union_(o);
        }
        return null;
    }

    /// The dimensions of the tensor, optionally named
    pub fn Shape(rcv: Tensor, j: usize) ?org.apache.arrow.flatbuf.TensorDim {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            var x = rcv._tab.vector(o);
            x += @as(u32, @intCast(j)) * 4;
            x = rcv._tab.indirect(x);
            return org.apache.arrow.flatbuf.TensorDim.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn ShapeLen(rcv: Tensor) u32 {
        const o = rcv._tab.offset(8);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    /// Non-negative byte offsets to advance one value cell along each dimension
    /// If omitted, default to row-major order (C-like).
    pub fn Strides(rcv: Tensor, j: usize) ?i64 {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.read(i64, a + @as(u32, @intCast(j)) * 8);
        }
        return 0;
    }

    pub fn StridesLen(rcv: Tensor) u32 {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn MutateStrides(rcv: Tensor, j: usize, n: i64) bool {
        const o = rcv._tab.offset(10);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.mutate(i64, a + @as(u32, @intCast(j)) * 8, n);
        }
        return false;
    }

    /// The location and size of the tensor's data
    pub fn Data(rcv: Tensor) ?org.apache.arrow.flatbuf.Buffer {
        const o = rcv._tab.offset(12);
        if (o != 0) {
            const x = o + rcv._tab.pos;
            return org.apache.arrow.flatbuf.Buffer.init(rcv._tab.bytes, x);
        }
        return null;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(5);
    }
    pub fn AddTypeType(__builder: *Builder, type_type: org.apache.arrow.flatbuf.Type.Tag) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.Type.Tag, 0, type_type, @as(org.apache.arrow.flatbuf.Type.Tag, @enumFromInt(0)));
    }

    pub fn AddType(__builder: *Builder, @"type": u32) !void {
        try __builder.prependSlotUOff(1, @"type", 0);
    }

    pub fn AddShape(__builder: *Builder, shape: u32) !void {
        try __builder.prependSlotUOff(2, shape, 0);
    }

    pub fn StartShapeVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 1);
    }
    pub fn AddStrides(__builder: *Builder, strides: u32) !void {
        try __builder.prependSlotUOff(3, strides, 0);
    }

    pub fn StartStridesVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(8, num_elems, 8);
    }
    pub fn AddData(__builder: *Builder, data: u32) !void {
        try __builder.prependSlotStruct(4, data, 0);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Tensor, __pack_opts: fb.common.PackOptions) !TensorT {
        return TensorT.Unpack(rcv, __pack_opts);
    }
    pub fn BufferHasIdentifier(buf: []const u8, off: u32) bool {
        return fb.BufferHasIdentifier(buf, off, __file_ident, false);
    }

    pub fn SizePrefixedBufferHasIdentifier(buf: []const u8, off: u32) bool {
        return fb.BufferHasIdentifier(buf, off, __file_ident, true);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.finishWithFileIdentifier(root, __file_ident);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.finishSizePrefixedWithFileIdentifier(root, __file_ident);
    }
};

test {
    var obj = TensorT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Tensor.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
