//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Tensor.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Tensor.fbs
//! file ident: //Tensor.fbs
//! typename    org.apache.arrow.flatbuf.TensorDim
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const TensorDim = @import("TensorDim.fb.zig").TensorDim;
                const TensorDimT = @import("TensorDim.fb.zig").TensorDimT;
            };
        };
    };
};

/// ----------------------------------------------------------------------
/// Data structures for dense tensors
/// Shape data for a single axis in a tensor
pub const TensorDimT = struct {
    /// Length of dimension
    size: i64 = 0,
    /// Name of the dimension, optional
    name: []const u8 = "",

    pub fn Pack(rcv: TensorDimT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        const name_off = if (rcv.name.len != 0) try __builder.createString(rcv.name) else 0;

        try TensorDim.Start(__builder);
        try TensorDim.AddSize(__builder, rcv.size);
        try TensorDim.AddName(__builder, name_off);
        return TensorDim.End(__builder);
    }

    pub fn UnpackTo(rcv: TensorDim, t: *TensorDimT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.size = rcv.Size();

        t.name = rcv.Name();
    }

    pub fn Unpack(rcv: TensorDim, __pack_opts: fb.common.PackOptions) fb.common.PackError!TensorDimT {
        var t = TensorDimT{};
        try TensorDimT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *TensorDimT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        // TODO __pack_opts.dupe_strings
        // if(self.name.len > 0) allocator.free(self.name);
    }
};

pub const TensorDim = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.TensorDim {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.TensorDim.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.TensorDim {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.TensorDim.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) TensorDim {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: TensorDim) fb.Table {
        return x._tab;
    }

    /// Length of dimension
    pub fn Size(rcv: TensorDim) i64 {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(i64, o + rcv._tab.pos);
        }
        return 0;
    }

    pub fn MutateSize(rcv: TensorDim, n: i64) bool {
        return rcv._tab.mutateSlot(i64, 4, n);
    }

    /// Name of the dimension, optional
    pub fn Name(rcv: TensorDim) []const u8 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.byteVector(o + rcv._tab.pos);
        }
        return "";
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(2);
    }
    pub fn AddSize(__builder: *Builder, size: i64) !void {
        try __builder.prependSlot(i64, 0, size, 0);
    }

    pub fn AddName(__builder: *Builder, name: u32) !void {
        try __builder.prependSlotUOff(1, name, 0);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: TensorDim, __pack_opts: fb.common.PackOptions) !TensorDimT {
        return TensorDimT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = TensorDimT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = TensorDim.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
