//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Time
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const TimeUnit = @import("TimeUnit.fb.zig").TimeUnit;
                const Time = @import("Time.fb.zig").Time;
                const TimeT = @import("Time.fb.zig").TimeT;
            };
        };
    };
};

/// Time is either a 32-bit or 64-bit signed integer type representing an
/// elapsed time since midnight, stored in either of four units: seconds,
/// milliseconds, microseconds or nanoseconds.
///
/// The integer `bitWidth` depends on the `unit` and must be one of the following:
/// * SECOND and MILLISECOND: 32 bits
/// * MICROSECOND and NANOSECOND: 64 bits
///
/// The allowed values are between 0 (inclusive) and 86400 (=24*60*60) seconds
/// (exclusive), adjusted for the time unit (for example, up to 86400000
/// exclusive for the MILLISECOND unit).
/// This definition doesn't allow for leap seconds. Time values from
/// measurements with leap seconds will need to be corrected when ingesting
/// into Arrow (for example by replacing the value 86400 with 86399).
pub const TimeT = struct {
    unit: org.apache.arrow.flatbuf.TimeUnit = @as(org.apache.arrow.flatbuf.TimeUnit, @enumFromInt(1)),
    bitWidth: i32 = 32,

    pub fn Pack(rcv: TimeT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        try Time.Start(__builder);
        try Time.AddUnit(__builder, rcv.unit);
        try Time.AddBitWidth(__builder, rcv.bitWidth);
        return Time.End(__builder);
    }

    pub fn UnpackTo(rcv: Time, t: *TimeT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.unit = rcv.Unit();

        t.bitWidth = rcv.BitWidth();
    }

    pub fn Unpack(rcv: Time, __pack_opts: fb.common.PackOptions) fb.common.PackError!TimeT {
        var t = TimeT{};
        try TimeT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *TimeT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
    }
};

pub const Time = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Time {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Time.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Time {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Time.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Time {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Time) fb.Table {
        return x._tab;
    }

    pub fn Unit(rcv: Time) org.apache.arrow.flatbuf.TimeUnit {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.TimeUnit, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.TimeUnit, @enumFromInt(1));
    }

    pub fn MutateUnit(rcv: Time, n: org.apache.arrow.flatbuf.TimeUnit) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.TimeUnit, 4, n);
    }

    pub fn BitWidth(rcv: Time) i32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.read(i32, o + rcv._tab.pos);
        }
        return 32;
    }

    pub fn MutateBitWidth(rcv: Time, n: i32) bool {
        return rcv._tab.mutateSlot(i32, 6, n);
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(2);
    }
    pub fn AddUnit(__builder: *Builder, unit: org.apache.arrow.flatbuf.TimeUnit) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.TimeUnit, 0, unit, @as(org.apache.arrow.flatbuf.TimeUnit, @enumFromInt(1)));
    }

    pub fn AddBitWidth(__builder: *Builder, bitWidth: i32) !void {
        try __builder.prependSlot(i32, 1, bitWidth, 32);
    }

    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Time, __pack_opts: fb.common.PackOptions) !TimeT {
        return TimeT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = TimeT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Time.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
