//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.TimeUnit
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const TimeUnit = @import("TimeUnit.fb.zig").TimeUnit;
            };
        };
    };
};

pub const TimeUnit = enum(i16) {
    SECOND = 0,
    MILLISECOND = 1,
    MICROSECOND = 2,
    NANOSECOND = 3,
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};
