//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Type
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const FixedSizeList = @import("FixedSizeList.fb.zig").FixedSizeList;
                const FixedSizeListT = @import("FixedSizeList.fb.zig").FixedSizeListT;
                const Interval = @import("Interval.fb.zig").Interval;
                const IntervalT = @import("Interval.fb.zig").IntervalT;
                const Null = @import("Null.fb.zig").Null;
                const NullT = @import("Null.fb.zig").NullT;
                const Utf8 = @import("Utf8.fb.zig").Utf8;
                const Utf8T = @import("Utf8.fb.zig").Utf8T;
                const LargeList = @import("LargeList.fb.zig").LargeList;
                const LargeListT = @import("LargeList.fb.zig").LargeListT;
                const Decimal = @import("Decimal.fb.zig").Decimal;
                const DecimalT = @import("Decimal.fb.zig").DecimalT;
                const Duration = @import("Duration.fb.zig").Duration;
                const DurationT = @import("Duration.fb.zig").DurationT;
                const Timestamp = @import("Timestamp.fb.zig").Timestamp;
                const TimestampT = @import("Timestamp.fb.zig").TimestampT;
                const Int = @import("Int.fb.zig").Int;
                const IntT = @import("Int.fb.zig").IntT;
                const LargeListView = @import("LargeListView.fb.zig").LargeListView;
                const LargeListViewT = @import("LargeListView.fb.zig").LargeListViewT;
                const List = @import("List.fb.zig").List;
                const ListT = @import("List.fb.zig").ListT;
                const Bool = @import("Bool.fb.zig").Bool;
                const BoolT = @import("Bool.fb.zig").BoolT;
                const Union = @import("Union.fb.zig").Union;
                const UnionT = @import("Union.fb.zig").UnionT;
                const RunEndEncoded = @import("RunEndEncoded.fb.zig").RunEndEncoded;
                const RunEndEncodedT = @import("RunEndEncoded.fb.zig").RunEndEncodedT;
                const Struct_ = @import("Struct_.fb.zig").Struct_;
                const Struct_T = @import("Struct_.fb.zig").Struct_T;
                const BinaryView = @import("BinaryView.fb.zig").BinaryView;
                const BinaryViewT = @import("BinaryView.fb.zig").BinaryViewT;
                const Binary = @import("Binary.fb.zig").Binary;
                const BinaryT = @import("Binary.fb.zig").BinaryT;
                const ListView = @import("ListView.fb.zig").ListView;
                const ListViewT = @import("ListView.fb.zig").ListViewT;
                const Type = @import("Type.fb.zig").Type;
                const Date = @import("Date.fb.zig").Date;
                const DateT = @import("Date.fb.zig").DateT;
                const Utf8View = @import("Utf8View.fb.zig").Utf8View;
                const Utf8ViewT = @import("Utf8View.fb.zig").Utf8ViewT;
                const LargeUtf8 = @import("LargeUtf8.fb.zig").LargeUtf8;
                const LargeUtf8T = @import("LargeUtf8.fb.zig").LargeUtf8T;
                const Map = @import("Map.fb.zig").Map;
                const MapT = @import("Map.fb.zig").MapT;
                const FloatingPoint = @import("FloatingPoint.fb.zig").FloatingPoint;
                const FloatingPointT = @import("FloatingPoint.fb.zig").FloatingPointT;
                const FixedSizeBinary = @import("FixedSizeBinary.fb.zig").FixedSizeBinary;
                const FixedSizeBinaryT = @import("FixedSizeBinary.fb.zig").FixedSizeBinaryT;
                const LargeBinary = @import("LargeBinary.fb.zig").LargeBinary;
                const LargeBinaryT = @import("LargeBinary.fb.zig").LargeBinaryT;
                const Time = @import("Time.fb.zig").Time;
                const TimeT = @import("Time.fb.zig").TimeT;
            };
        };
    };
};

/// ----------------------------------------------------------------------
/// Top-level Type value, enabling extensible type-specific metadata. We can
/// add new logical types to Type without breaking backwards compatibility
pub const Type = union(enum) {
    NONE,
    Null: org.apache.arrow.flatbuf.Null,
    Int: org.apache.arrow.flatbuf.Int,
    FloatingPoint: org.apache.arrow.flatbuf.FloatingPoint,
    Binary: org.apache.arrow.flatbuf.Binary,
    Utf8: org.apache.arrow.flatbuf.Utf8,
    Bool: org.apache.arrow.flatbuf.Bool,
    Decimal: org.apache.arrow.flatbuf.Decimal,
    Date: org.apache.arrow.flatbuf.Date,
    Time: org.apache.arrow.flatbuf.Time,
    Timestamp: org.apache.arrow.flatbuf.Timestamp,
    Interval: org.apache.arrow.flatbuf.Interval,
    List: org.apache.arrow.flatbuf.List,
    Struct_: org.apache.arrow.flatbuf.Struct_,
    Union: org.apache.arrow.flatbuf.Union,
    FixedSizeBinary: org.apache.arrow.flatbuf.FixedSizeBinary,
    FixedSizeList: org.apache.arrow.flatbuf.FixedSizeList,
    Map: org.apache.arrow.flatbuf.Map,
    Duration: org.apache.arrow.flatbuf.Duration,
    LargeBinary: org.apache.arrow.flatbuf.LargeBinary,
    LargeUtf8: org.apache.arrow.flatbuf.LargeUtf8,
    LargeList: org.apache.arrow.flatbuf.LargeList,
    RunEndEncoded: org.apache.arrow.flatbuf.RunEndEncoded,
    BinaryView: org.apache.arrow.flatbuf.BinaryView,
    Utf8View: org.apache.arrow.flatbuf.Utf8View,
    ListView: org.apache.arrow.flatbuf.ListView,
    LargeListView: org.apache.arrow.flatbuf.LargeListView,

    pub const Tag = std.meta.Tag(@This());
    pub fn tagName(v: @This()) []const u8 {
        return @tagName(v);
    }
};

pub const TypeT = union(Type.Tag) {
    NONE: void,
    Null: ?*org.apache.arrow.flatbuf.NullT,
    Int: ?*org.apache.arrow.flatbuf.IntT,
    FloatingPoint: ?*org.apache.arrow.flatbuf.FloatingPointT,
    Binary: ?*org.apache.arrow.flatbuf.BinaryT,
    Utf8: ?*org.apache.arrow.flatbuf.Utf8T,
    Bool: ?*org.apache.arrow.flatbuf.BoolT,
    Decimal: ?*org.apache.arrow.flatbuf.DecimalT,
    Date: ?*org.apache.arrow.flatbuf.DateT,
    Time: ?*org.apache.arrow.flatbuf.TimeT,
    Timestamp: ?*org.apache.arrow.flatbuf.TimestampT,
    Interval: ?*org.apache.arrow.flatbuf.IntervalT,
    List: ?*org.apache.arrow.flatbuf.ListT,
    Struct_: ?*org.apache.arrow.flatbuf.Struct_T,
    Union: ?*org.apache.arrow.flatbuf.UnionT,
    FixedSizeBinary: ?*org.apache.arrow.flatbuf.FixedSizeBinaryT,
    FixedSizeList: ?*org.apache.arrow.flatbuf.FixedSizeListT,
    Map: ?*org.apache.arrow.flatbuf.MapT,
    Duration: ?*org.apache.arrow.flatbuf.DurationT,
    LargeBinary: ?*org.apache.arrow.flatbuf.LargeBinaryT,
    LargeUtf8: ?*org.apache.arrow.flatbuf.LargeUtf8T,
    LargeList: ?*org.apache.arrow.flatbuf.LargeListT,
    RunEndEncoded: ?*org.apache.arrow.flatbuf.RunEndEncodedT,
    BinaryView: ?*org.apache.arrow.flatbuf.BinaryViewT,
    Utf8View: ?*org.apache.arrow.flatbuf.Utf8ViewT,
    ListView: ?*org.apache.arrow.flatbuf.ListViewT,
    LargeListView: ?*org.apache.arrow.flatbuf.LargeListViewT,

    pub fn deinit(self: *TypeT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        switch (self.*) {
            .NONE => {},
            .Null => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Null = null;
            },
            .Int => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Int = null;
            },
            .FloatingPoint => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.FloatingPoint = null;
            },
            .Binary => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Binary = null;
            },
            .Utf8 => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Utf8 = null;
            },
            .Bool => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Bool = null;
            },
            .Decimal => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Decimal = null;
            },
            .Date => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Date = null;
            },
            .Time => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Time = null;
            },
            .Timestamp => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Timestamp = null;
            },
            .Interval => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Interval = null;
            },
            .List => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.List = null;
            },
            .Struct_ => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Struct_ = null;
            },
            .Union => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Union = null;
            },
            .FixedSizeBinary => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.FixedSizeBinary = null;
            },
            .FixedSizeList => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.FixedSizeList = null;
            },
            .Map => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Map = null;
            },
            .Duration => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Duration = null;
            },
            .LargeBinary => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.LargeBinary = null;
            },
            .LargeUtf8 => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.LargeUtf8 = null;
            },
            .LargeList => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.LargeList = null;
            },
            .RunEndEncoded => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.RunEndEncoded = null;
            },
            .BinaryView => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.BinaryView = null;
            },
            .Utf8View => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.Utf8View = null;
            },
            .ListView => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.ListView = null;
            },
            .LargeListView => |mptr| if (mptr) |x| {
                x.deinit(allocator);
                allocator.destroy(x);
                self.LargeListView = null;
            },
        }
    }

    pub fn Pack(rcv: TypeT, __builder: *Builder, __pack_opts: fb.common.PackOptions) !u32 {
        _ = .{ __builder, __pack_opts };
        // std.debug.print("pack() TypeT rcv=.{s}\n", .{@tagName(rcv)});
        switch (rcv) {
            .NONE => {},
            .Null => |x| return x.?.Pack(__builder, __pack_opts),
            .Int => |x| return x.?.Pack(__builder, __pack_opts),
            .FloatingPoint => |x| return x.?.Pack(__builder, __pack_opts),
            .Binary => |x| return x.?.Pack(__builder, __pack_opts),
            .Utf8 => |x| return x.?.Pack(__builder, __pack_opts),
            .Bool => |x| return x.?.Pack(__builder, __pack_opts),
            .Decimal => |x| return x.?.Pack(__builder, __pack_opts),
            .Date => |x| return x.?.Pack(__builder, __pack_opts),
            .Time => |x| return x.?.Pack(__builder, __pack_opts),
            .Timestamp => |x| return x.?.Pack(__builder, __pack_opts),
            .Interval => |x| return x.?.Pack(__builder, __pack_opts),
            .List => |x| return x.?.Pack(__builder, __pack_opts),
            .Struct_ => |x| return x.?.Pack(__builder, __pack_opts),
            .Union => |x| return x.?.Pack(__builder, __pack_opts),
            .FixedSizeBinary => |x| return x.?.Pack(__builder, __pack_opts),
            .FixedSizeList => |x| return x.?.Pack(__builder, __pack_opts),
            .Map => |x| return x.?.Pack(__builder, __pack_opts),
            .Duration => |x| return x.?.Pack(__builder, __pack_opts),
            .LargeBinary => |x| return x.?.Pack(__builder, __pack_opts),
            .LargeUtf8 => |x| return x.?.Pack(__builder, __pack_opts),
            .LargeList => |x| return x.?.Pack(__builder, __pack_opts),
            .RunEndEncoded => |x| return x.?.Pack(__builder, __pack_opts),
            .BinaryView => |x| return x.?.Pack(__builder, __pack_opts),
            .Utf8View => |x| return x.?.Pack(__builder, __pack_opts),
            .ListView => |x| return x.?.Pack(__builder, __pack_opts),
            .LargeListView => |x| return x.?.Pack(__builder, __pack_opts),
        }
        return 0;
    }

    pub fn Unpack(rcv: Type.Tag, table: fb.Table, __pack_opts: fb.common.PackOptions) !TypeT {
        _ = .{ table, __pack_opts };
        // std.debug.print("unpack() Type rcv=.{s}\n", .{@tagName(rcv)});
        switch (rcv) {
            .NONE => return .NONE,
            .Null => {
                const x = org.apache.arrow.flatbuf.Null.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.NullT);
                ptr.* = try org.apache.arrow.flatbuf.NullT.Unpack(x, __pack_opts);
                return .{ .Null = ptr };
            },
            .Int => {
                const x = org.apache.arrow.flatbuf.Int.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntT);
                ptr.* = try org.apache.arrow.flatbuf.IntT.Unpack(x, __pack_opts);
                return .{ .Int = ptr };
            },
            .FloatingPoint => {
                const x = org.apache.arrow.flatbuf.FloatingPoint.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.FloatingPointT);
                ptr.* = try org.apache.arrow.flatbuf.FloatingPointT.Unpack(x, __pack_opts);
                return .{ .FloatingPoint = ptr };
            },
            .Binary => {
                const x = org.apache.arrow.flatbuf.Binary.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BinaryT);
                ptr.* = try org.apache.arrow.flatbuf.BinaryT.Unpack(x, __pack_opts);
                return .{ .Binary = ptr };
            },
            .Utf8 => {
                const x = org.apache.arrow.flatbuf.Utf8.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.Utf8T);
                ptr.* = try org.apache.arrow.flatbuf.Utf8T.Unpack(x, __pack_opts);
                return .{ .Utf8 = ptr };
            },
            .Bool => {
                const x = org.apache.arrow.flatbuf.Bool.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BoolT);
                ptr.* = try org.apache.arrow.flatbuf.BoolT.Unpack(x, __pack_opts);
                return .{ .Bool = ptr };
            },
            .Decimal => {
                const x = org.apache.arrow.flatbuf.Decimal.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.DecimalT);
                ptr.* = try org.apache.arrow.flatbuf.DecimalT.Unpack(x, __pack_opts);
                return .{ .Decimal = ptr };
            },
            .Date => {
                const x = org.apache.arrow.flatbuf.Date.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.DateT);
                ptr.* = try org.apache.arrow.flatbuf.DateT.Unpack(x, __pack_opts);
                return .{ .Date = ptr };
            },
            .Time => {
                const x = org.apache.arrow.flatbuf.Time.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.TimeT);
                ptr.* = try org.apache.arrow.flatbuf.TimeT.Unpack(x, __pack_opts);
                return .{ .Time = ptr };
            },
            .Timestamp => {
                const x = org.apache.arrow.flatbuf.Timestamp.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.TimestampT);
                ptr.* = try org.apache.arrow.flatbuf.TimestampT.Unpack(x, __pack_opts);
                return .{ .Timestamp = ptr };
            },
            .Interval => {
                const x = org.apache.arrow.flatbuf.Interval.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.IntervalT);
                ptr.* = try org.apache.arrow.flatbuf.IntervalT.Unpack(x, __pack_opts);
                return .{ .Interval = ptr };
            },
            .List => {
                const x = org.apache.arrow.flatbuf.List.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.ListT);
                ptr.* = try org.apache.arrow.flatbuf.ListT.Unpack(x, __pack_opts);
                return .{ .List = ptr };
            },
            .Struct_ => {
                const x = org.apache.arrow.flatbuf.Struct_.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.Struct_T);
                ptr.* = try org.apache.arrow.flatbuf.Struct_T.Unpack(x, __pack_opts);
                return .{ .Struct_ = ptr };
            },
            .Union => {
                const x = org.apache.arrow.flatbuf.Union.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.UnionT);
                ptr.* = try org.apache.arrow.flatbuf.UnionT.Unpack(x, __pack_opts);
                return .{ .Union = ptr };
            },
            .FixedSizeBinary => {
                const x = org.apache.arrow.flatbuf.FixedSizeBinary.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.FixedSizeBinaryT);
                ptr.* = try org.apache.arrow.flatbuf.FixedSizeBinaryT.Unpack(x, __pack_opts);
                return .{ .FixedSizeBinary = ptr };
            },
            .FixedSizeList => {
                const x = org.apache.arrow.flatbuf.FixedSizeList.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.FixedSizeListT);
                ptr.* = try org.apache.arrow.flatbuf.FixedSizeListT.Unpack(x, __pack_opts);
                return .{ .FixedSizeList = ptr };
            },
            .Map => {
                const x = org.apache.arrow.flatbuf.Map.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.MapT);
                ptr.* = try org.apache.arrow.flatbuf.MapT.Unpack(x, __pack_opts);
                return .{ .Map = ptr };
            },
            .Duration => {
                const x = org.apache.arrow.flatbuf.Duration.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.DurationT);
                ptr.* = try org.apache.arrow.flatbuf.DurationT.Unpack(x, __pack_opts);
                return .{ .Duration = ptr };
            },
            .LargeBinary => {
                const x = org.apache.arrow.flatbuf.LargeBinary.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.LargeBinaryT);
                ptr.* = try org.apache.arrow.flatbuf.LargeBinaryT.Unpack(x, __pack_opts);
                return .{ .LargeBinary = ptr };
            },
            .LargeUtf8 => {
                const x = org.apache.arrow.flatbuf.LargeUtf8.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.LargeUtf8T);
                ptr.* = try org.apache.arrow.flatbuf.LargeUtf8T.Unpack(x, __pack_opts);
                return .{ .LargeUtf8 = ptr };
            },
            .LargeList => {
                const x = org.apache.arrow.flatbuf.LargeList.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.LargeListT);
                ptr.* = try org.apache.arrow.flatbuf.LargeListT.Unpack(x, __pack_opts);
                return .{ .LargeList = ptr };
            },
            .RunEndEncoded => {
                const x = org.apache.arrow.flatbuf.RunEndEncoded.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.RunEndEncodedT);
                ptr.* = try org.apache.arrow.flatbuf.RunEndEncodedT.Unpack(x, __pack_opts);
                return .{ .RunEndEncoded = ptr };
            },
            .BinaryView => {
                const x = org.apache.arrow.flatbuf.BinaryView.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.BinaryViewT);
                ptr.* = try org.apache.arrow.flatbuf.BinaryViewT.Unpack(x, __pack_opts);
                return .{ .BinaryView = ptr };
            },
            .Utf8View => {
                const x = org.apache.arrow.flatbuf.Utf8View.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.Utf8ViewT);
                ptr.* = try org.apache.arrow.flatbuf.Utf8ViewT.Unpack(x, __pack_opts);
                return .{ .Utf8View = ptr };
            },
            .ListView => {
                const x = org.apache.arrow.flatbuf.ListView.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.ListViewT);
                ptr.* = try org.apache.arrow.flatbuf.ListViewT.Unpack(x, __pack_opts);
                return .{ .ListView = ptr };
            },
            .LargeListView => {
                const x = org.apache.arrow.flatbuf.LargeListView.init(table.bytes, table.pos);
                const ptr = try __pack_opts.allocator.?.create(org.apache.arrow.flatbuf.LargeListViewT);
                ptr.* = try org.apache.arrow.flatbuf.LargeListViewT.Unpack(x, __pack_opts);
                return .{ .LargeListView = ptr };
            },
        }
        unreachable;
    }
};

test {
    var obj: TypeT = .NONE;
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    const table = fb.Table.init(bytes, 0);
    const obj2 = try TypeT.Unpack(.NONE, table, opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
