//!
//! generated by flatc-zig
//! binary:     .zig-cache/flatc-zig/Users/sh01312ml/opencode/zarrow/src/format/Schema.bfbs
//! schema:     /Users/sh01312ml/opencode/zarrow/src/format/Schema.fbs
//! file ident: //Schema.fbs
//! typename    org.apache.arrow.flatbuf.Union
//!

const std = @import("std");
const fb = @import("flatbufferz");
const Builder = fb.Builder;

// a namespace generated by flatc-zig to match typenames produced by flatc
const org = struct {
    const apache = struct {
        const arrow = struct {
            const flatbuf = struct {
                const UnionMode = @import("UnionMode.fb.zig").UnionMode;
                const Union = @import("Union.fb.zig").Union;
                const UnionT = @import("Union.fb.zig").UnionT;
            };
        };
    };
};

/// A union is a complex type with children in Field
/// By default ids in the type vector refer to the offsets in the children
/// optionally typeIds provides an indirection between the child offset and the type id
/// for each child `typeIds[offset]` is the id used in the type vector
pub const UnionT = struct {
    mode: org.apache.arrow.flatbuf.UnionMode = @as(org.apache.arrow.flatbuf.UnionMode, @enumFromInt(0)),
    typeIds: std.ArrayList(i32) = .{},

    pub fn Pack(rcv: UnionT, __builder: *Builder, __pack_opts: fb.common.PackOptions) fb.common.PackError!u32 {
        _ = .{__pack_opts};
        var __tmp_offsets = std.ArrayList(u32){};
        defer if (__pack_opts.allocator) |alloc| __tmp_offsets.deinit(alloc);
        var typeIds_off: u32 = 0;
        if (rcv.typeIds.items.len != 0) {
            const typeIds_len: i32 = @intCast(rcv.typeIds.items.len);
            _ = try Union.StartTypeIdsVector(__builder, typeIds_len);
            {
                var j = typeIds_len - 1;
                while (j >= 0) : (j -= 1) {
                    try __builder.prepend(i32, rcv.typeIds.items[@as(u32, @bitCast(j))]);
                }
                typeIds_off = try __builder.endVector(@bitCast(typeIds_len));
            }
        }

        try Union.Start(__builder);
        try Union.AddMode(__builder, rcv.mode);
        try Union.AddTypeIds(__builder, typeIds_off);
        return Union.End(__builder);
    }

    pub fn UnpackTo(rcv: Union, t: *UnionT, __pack_opts: fb.common.PackOptions) !void {
        _ = .{__pack_opts};
        t.mode = rcv.Mode();

        const typeIds_len = rcv.TypeIdsLen();
        t.typeIds = try std.ArrayList(i32).initCapacity(__pack_opts.allocator.?, @as(u32, @bitCast(typeIds_len)));
        t.typeIds.expandToCapacity();
        {
            var j: u32 = 0;
            while (j < typeIds_len) : (j += 1) {
                t.typeIds.items[j] = rcv.TypeIds(j).?;
            }
        }
    }

    pub fn Unpack(rcv: Union, __pack_opts: fb.common.PackOptions) fb.common.PackError!UnionT {
        var t = UnionT{};
        try UnionT.UnpackTo(rcv, &t, __pack_opts);
        return t;
    }

    pub fn deinit(self: *UnionT, allocator: std.mem.Allocator) void {
        _ = .{ self, allocator };
        self.typeIds.deinit(allocator);
    }
};

pub const Union = struct {
    _tab: fb.Table,

    pub fn GetRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Union {
        const n = fb.encode.read(u32, buf[offset..]);
        return org.apache.arrow.flatbuf.Union.init(buf, n + offset);
    }

    pub fn GetSizePrefixedRootAs(buf: []u8, offset: u32) org.apache.arrow.flatbuf.Union {
        const n = fb.encode.read(u32, buf[offset + fb.Builder.size_u32 ..]);
        return org.apache.arrow.flatbuf.Union.init(buf, n + offset + fb.Builder.size_u32);
    }

    pub fn init(bytes: []u8, pos: u32) Union {
        return .{ ._tab = .{ .bytes = bytes, .pos = pos } };
    }

    pub fn Table(x: Union) fb.Table {
        return x._tab;
    }

    pub fn Mode(rcv: Union) org.apache.arrow.flatbuf.UnionMode {
        const o = rcv._tab.offset(4);
        if (o != 0) {
            return rcv._tab.read(org.apache.arrow.flatbuf.UnionMode, o + rcv._tab.pos);
        }
        return @as(org.apache.arrow.flatbuf.UnionMode, @enumFromInt(0));
    }

    pub fn MutateMode(rcv: Union, n: org.apache.arrow.flatbuf.UnionMode) bool {
        return rcv._tab.mutateSlot(org.apache.arrow.flatbuf.UnionMode, 4, n);
    }

    pub fn TypeIds(rcv: Union, j: usize) ?i32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.read(i32, a + @as(u32, @intCast(j)) * 4);
        }
        return 0;
    }

    pub fn TypeIdsLen(rcv: Union) u32 {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            return rcv._tab.vectorLen(o);
        }
        return 0;
    }

    pub fn MutateTypeIds(rcv: Union, j: usize, n: i32) bool {
        const o = rcv._tab.offset(6);
        if (o != 0) {
            const a = rcv._tab.vector(o);
            return rcv._tab.mutate(i32, a + @as(u32, @intCast(j)) * 4, n);
        }
        return false;
    }

    pub fn Start(__builder: *Builder) !void {
        try __builder.startObject(2);
    }
    pub fn AddMode(__builder: *Builder, mode: org.apache.arrow.flatbuf.UnionMode) !void {
        try __builder.prependSlot(org.apache.arrow.flatbuf.UnionMode, 0, mode, @as(org.apache.arrow.flatbuf.UnionMode, @enumFromInt(0)));
    }

    pub fn AddTypeIds(__builder: *Builder, typeIds: u32) !void {
        try __builder.prependSlotUOff(1, typeIds, 0);
    }

    pub fn StartTypeIdsVector(__builder: *Builder, num_elems: i32) !u32 {
        return __builder.startVector(4, num_elems, 4);
    }
    pub fn End(__builder: *Builder) !u32 {
        return __builder.endObject();
    }

    pub fn Unpack(rcv: Union, __pack_opts: fb.common.PackOptions) !UnionT {
        return UnionT.Unpack(rcv, __pack_opts);
    }
    pub fn FinishBuffer(__builder: *Builder, root: u32) !void {
        return __builder.Finish(root);
    }

    pub fn FinishSizePrefixedBuffer(__builder: *Builder, root: u32) !void {
        return __builder.FinishSizePrefixed(root);
    }
};

test {
    var obj = UnionT{};
    var b = Builder.init(std.testing.allocator);
    defer b.deinitAll();
    const opts: fb.common.PackOptions = .{ .allocator = std.testing.allocator };
    const end = try obj.Pack(&b, opts);
    try b.finish(end);
    const bytes = try b.finishedBytes();
    var obj_packed = Union.GetRootAs(bytes, 0);
    const obj2 = try obj_packed.Unpack(opts);
    var b2 = Builder.init(std.testing.allocator);
    defer b2.deinitAll();
    const end2 = try obj2.Pack(&b2, opts);
    try b2.finish(end2);
    try std.testing.expectEqualStrings(bytes, try b2.finishedBytes());
}
