const datatype = @import("../datatype.zig");

pub const DataType = datatype.DataType;
pub const ArrayData = @import("array_data.zig").ArrayData;
pub const PrimitiveArray = @import("primitive_array.zig").PrimitiveArray;
pub const PrimitiveBuilder = @import("primitive_array.zig").PrimitiveBuilder;
pub const Int8Array = PrimitiveArray(i8);
pub const Int16Array = PrimitiveArray(i16);
pub const Int32Array = PrimitiveArray(i32);
pub const Int64Array = PrimitiveArray(i64);
pub const UInt8Array = PrimitiveArray(u8);
pub const UInt16Array = PrimitiveArray(u16);
pub const UInt32Array = PrimitiveArray(u32);
pub const UInt64Array = PrimitiveArray(u64);
pub const Float32Array = PrimitiveArray(f32);
pub const Float64Array = PrimitiveArray(f64);
pub const Int8Builder = PrimitiveBuilder(i8, DataType{ .int8 = {} });
pub const Int16Builder = PrimitiveBuilder(i16, DataType{ .int16 = {} });
pub const Int32Builder = PrimitiveBuilder(i32, DataType{ .int32 = {} });
pub const Int64Builder = PrimitiveBuilder(i64, DataType{ .int64 = {} });
pub const UInt8Builder = PrimitiveBuilder(u8, DataType{ .uint8 = {} });
pub const UInt16Builder = PrimitiveBuilder(u16, DataType{ .uint16 = {} });
pub const UInt32Builder = PrimitiveBuilder(u32, DataType{ .uint32 = {} });
pub const UInt64Builder = PrimitiveBuilder(u64, DataType{ .uint64 = {} });
pub const Float32Builder = PrimitiveBuilder(f32, DataType{ .float = {} });
pub const Float64Builder = PrimitiveBuilder(f64, DataType{ .double = {} });
pub const BooleanArray = @import("boolean_array.zig").BooleanArray;
pub const BooleanBuilder = @import("boolean_array.zig").BooleanBuilder;
pub const StringArray = @import("string_array.zig").StringArray;
pub const StringBuilder = @import("string_array.zig").StringBuilder;
pub const BinaryArray = @import("binary_array.zig").BinaryArray;
pub const BinaryBuilder = @import("binary_array.zig").BinaryBuilder;
